
package com.inov8.integration.middleware.bop.avenza;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-12-21T23:43:31.803-08:00
 * Generated source version: 3.1.6
 * 
 */
public final class ServiceSoap_ServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://BOP_MobileApp.org", "Service");

    private ServiceSoap_ServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Service ss = new Service(wsdlURL, SERVICE_NAME);
        ServiceSoap port = ss.getServiceSoap();  
        
        {
        System.out.println("Invoking emailAccountStatement...");
        com.inov8.integration.middleware.bop.avenza.EmailAccountStatementRequest _emailAccountStatement_parameters = null;
        com.inov8.integration.middleware.bop.avenza.EmailAccountStatementResponse _emailAccountStatement__return = port.emailAccountStatement(_emailAccountStatement_parameters);
        System.out.println("emailAccountStatement.result=" + _emailAccountStatement__return);


        }
        {
        System.out.println("Invoking customerEmailUpdate...");
        com.inov8.integration.middleware.bop.avenza.CustomerEmailUpdateRequest _customerEmailUpdate_parameters = null;
        com.inov8.integration.middleware.bop.avenza.CustomerEmailUpdateResponse _customerEmailUpdate__return = port.customerEmailUpdate(_customerEmailUpdate_parameters);
        System.out.println("customerEmailUpdate.result=" + _customerEmailUpdate__return);


        }
        {
        System.out.println("Invoking customerEmailVerification...");
        com.inov8.integration.middleware.bop.avenza.CustomerEmailVerificationRequest _customerEmailVerification_parameters = null;
        com.inov8.integration.middleware.bop.avenza.CustomerEmailVerificationResponse _customerEmailVerification__return = port.customerEmailVerification(_customerEmailVerification_parameters);
        System.out.println("customerEmailVerification.result=" + _customerEmailVerification__return);


        }
        {
        System.out.println("Invoking viewAccountStatement...");
        com.inov8.integration.middleware.bop.avenza.ViewAccountStatementRequest _viewAccountStatement_parameters = null;
        com.inov8.integration.middleware.bop.avenza.ViewAccountStatementResponse _viewAccountStatement__return = port.viewAccountStatement(_viewAccountStatement_parameters);
        System.out.println("viewAccountStatement.result=" + _viewAccountStatement__return);


        }

        System.exit(0);
    }

}
