package com.inov8.integration.middleware.abl.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-01-19T16:31:33.147+05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IService1")
@XmlSeeAlso({ObjectFactory.class})
public interface IService1 {

    @WebMethod(operationName = "FundsTransfer", action = "http://tempuri.org/IService1/FundsTransfer")
    @Action(input = "http://tempuri.org/IService1/FundsTransfer", output = "http://tempuri.org/IService1/FundsTransferResponse")
    @RequestWrapper(localName = "FundsTransfer", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.client.FundsTransfer")
    @ResponseWrapper(localName = "FundsTransferResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.client.FundsTransferResponse")
    @WebResult(name = "FundsTransferResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String fundsTransfer(
        @WebParam(name = "PAN", targetNamespace = "http://tempuri.org/")
        java.lang.String pan,
        @WebParam(name = "sFrmAcc", targetNamespace = "http://tempuri.org/")
        java.lang.String sFrmAcc,
        @WebParam(name = "sFrmAccType", targetNamespace = "http://tempuri.org/")
        java.lang.String sFrmAccType,
        @WebParam(name = "sToAcc", targetNamespace = "http://tempuri.org/")
        java.lang.String sToAcc,
        @WebParam(name = "sToAccType", targetNamespace = "http://tempuri.org/")
        java.lang.String sToAccType,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        java.lang.String amount,
        @WebParam(name = "RRN", targetNamespace = "http://tempuri.org/")
        java.lang.String rrn,
        @WebParam(name = "sNarration", targetNamespace = "http://tempuri.org/")
        java.lang.String sNarration,
        @WebParam(name = "OriginalTransactionDateTime", targetNamespace = "http://tempuri.org/")
        java.lang.String originalTransactionDateTime,
        @WebParam(name = "Commission", targetNamespace = "http://tempuri.org/")
        java.lang.String commission
    );

    @WebMethod(operationName = "FTReversal", action = "http://tempuri.org/IService1/FTReversal")
    @Action(input = "http://tempuri.org/IService1/FTReversal", output = "http://tempuri.org/IService1/FTReversalResponse")
    @RequestWrapper(localName = "FTReversal", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.client.FTReversal")
    @ResponseWrapper(localName = "FTReversalResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.client.FTReversalResponse")
    @WebResult(name = "FundsReversalResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String ftReversal(
        @WebParam(name = "PAN", targetNamespace = "http://tempuri.org/")
        java.lang.String pan,
        @WebParam(name = "sFrmAcc", targetNamespace = "http://tempuri.org/")
        java.lang.String sFrmAcc,
        @WebParam(name = "sFrmAccType", targetNamespace = "http://tempuri.org/")
        java.lang.String sFrmAccType,
        @WebParam(name = "sToAcc", targetNamespace = "http://tempuri.org/")
        java.lang.String sToAcc,
        @WebParam(name = "sToAccType", targetNamespace = "http://tempuri.org/")
        java.lang.String sToAccType,
        @WebParam(name = "Amount", targetNamespace = "http://tempuri.org/")
        java.lang.String amount,
        @WebParam(name = "RRN", targetNamespace = "http://tempuri.org/")
        java.lang.String rrn,
        @WebParam(name = "sNarration", targetNamespace = "http://tempuri.org/")
        java.lang.String sNarration,
        @WebParam(name = "OriginalSTAN", targetNamespace = "http://tempuri.org/")
        java.lang.String originalSTAN,
        @WebParam(name = "CurrentTransactionDateTime", targetNamespace = "http://tempuri.org/")
        java.lang.String currentTransactionDateTime,
        @WebParam(name = "OriginalTransactionDateTime", targetNamespace = "http://tempuri.org/")
        java.lang.String originalTransactionDateTime,
        @WebParam(name = "OriginalTransmittionDateTime", targetNamespace = "http://tempuri.org/")
        java.lang.String originalTransmittionDateTime,
        @WebParam(name = "Commission", targetNamespace = "http://tempuri.org/")
        java.lang.String commission
    );

    @WebMethod(operationName = "CustAcctDetail", action = "http://tempuri.org/IService1/CustAcctDetail")
    @Action(input = "http://tempuri.org/IService1/CustAcctDetail", output = "http://tempuri.org/IService1/CustAcctDetailResponse")
    @RequestWrapper(localName = "CustAcctDetail", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.client.CustAcctDetail")
    @ResponseWrapper(localName = "CustAcctDetailResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.client.CustAcctDetailResponse")
    public void custAcctDetail(
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        java.lang.String userid,
        @WebParam(mode = WebParam.Mode.OUT, name = "CNIC", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> cnic,
        @WebParam(mode = WebParam.Mode.OUT, name = "CUSTNAME", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> custname,
        @WebParam(mode = WebParam.Mode.OUT, name = "EMAIL", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> email,
        @WebParam(mode = WebParam.Mode.OUT, name = "MOBNO", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> mobno,
        @WebParam(mode = WebParam.Mode.OUT, name = "IBAN", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> iban,
        @WebParam(mode = WebParam.Mode.OUT, name = "ACCTCURRENY", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> acctcurreny,
        @WebParam(mode = WebParam.Mode.OUT, name = "CURRENYMNEMONIC", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> currenymnemonic,
        @WebParam(mode = WebParam.Mode.OUT, name = "AVAILABLEBALANCE", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> availablebalance,
        @WebParam(mode = WebParam.Mode.OUT, name = "CURRENTBALANCE", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> currentbalance,
        @WebParam(mode = WebParam.Mode.OUT, name = "ACCTTYPE", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> accttype,
        @WebParam(mode = WebParam.Mode.OUT, name = "BRANCHCODE", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> branchcode,
        @WebParam(mode = WebParam.Mode.OUT, name = "BRANCHNAME", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> branchname,
        @WebParam(mode = WebParam.Mode.OUT, name = "ACCOUTNAME", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> accoutname,
        @WebParam(mode = WebParam.Mode.OUT, name = "BANKIMD", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<java.lang.String> bankimd,
        @WebParam(mode = WebParam.Mode.OUT, name = "ACCNO", targetNamespace = "http://tempuri.org/")
        javax.xml.ws.Holder<com.inov8.integration.middleware.abl.client.CustAcctDetailResponse.ACCNO> accno
    );

    @WebMethod(operationName = "BillPayment", action = "http://tempuri.org/IService1/BillPayment")
    @Action(input = "http://tempuri.org/IService1/BillPayment", output = "http://tempuri.org/IService1/BillPaymentResponse")
    @RequestWrapper(localName = "BillPayment", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.client.BillPayment")
    @ResponseWrapper(localName = "BillPaymentResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.client.BillPaymentResponse")
    @WebResult(name = "BillPaymentResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String billPayment(
        @WebParam(name = "CustomerID", targetNamespace = "http://tempuri.org/")
        java.lang.String customerID,
        @WebParam(name = "UtilityComapanyId", targetNamespace = "http://tempuri.org/")
        java.lang.String utilityComapanyId,
        @WebParam(name = "ConsumerNo", targetNamespace = "http://tempuri.org/")
        java.lang.String consumerNo,
        @WebParam(name = "amountpaid", targetNamespace = "http://tempuri.org/")
        java.lang.String amountpaid,
        @WebParam(name = "FromAccount", targetNamespace = "http://tempuri.org/")
        java.lang.String fromAccount,
        @WebParam(name = "FromAccountType", targetNamespace = "http://tempuri.org/")
        java.lang.String fromAccountType,
        @WebParam(name = "RRN", targetNamespace = "http://tempuri.org/")
        java.lang.String rrn
    );

    @WebMethod(operationName = "BillInquiry", action = "http://tempuri.org/IService1/BillInquiry")
    @Action(input = "http://tempuri.org/IService1/BillInquiry", output = "http://tempuri.org/IService1/BillInquiryResponse")
    @RequestWrapper(localName = "BillInquiry", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.client.BillInquiry")
    @ResponseWrapper(localName = "BillInquiryResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.client.BillInquiryResponse")
    @WebResult(name = "BillInquiryResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String billInquiry(
        @WebParam(name = "CustomerID", targetNamespace = "http://tempuri.org/")
        java.lang.String customerID,
        @WebParam(name = "UtilityComapanyId", targetNamespace = "http://tempuri.org/")
        java.lang.String utilityComapanyId,
        @WebParam(name = "ConsumerNo", targetNamespace = "http://tempuri.org/")
        java.lang.String consumerNo,
        @WebParam(name = "RRN", targetNamespace = "http://tempuri.org/")
        java.lang.String rrn
    );
}
