package com.inov8.integration.channel.JSBLB.ETPaymentCollection.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-10-27T21:38:00.065+05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://TaxManagementSystem/", name = "TaxInquirySoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TaxInquirySoap {

    @WebMethod(operationName = "GetAssesmentDetail", action = "http://TaxManagementSystem/GetAssesmentDetail")
    @RequestWrapper(localName = "GetAssesmentDetail", targetNamespace = "http://TaxManagementSystem/", className = "com.inov8.integration.channel.JSBLB.ETPaymentCollection.client.GetAssesmentDetail")
    @ResponseWrapper(localName = "GetAssesmentDetailResponse", targetNamespace = "http://TaxManagementSystem/", className = "com.inov8.integration.channel.JSBLB.ETPaymentCollection.client.GetAssesmentDetailResponse")
    @WebResult(name = "GetAssesmentDetailResult", targetNamespace = "http://TaxManagementSystem/")
    public com.inov8.integration.channel.JSBLB.ETPaymentCollection.client.AssesmentDetails getAssesmentDetail(
        @WebParam(name = "RegisterationNumber", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String registerationNumber,
        @WebParam(name = "ChesisNumber", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String chesisNumber,
        @WebParam(name = "BankMnemonic", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String bankMnemonic
    );

    @WebMethod(operationName = "CancelChallan", action = "http://TaxManagementSystem/CancelChallan")
    @RequestWrapper(localName = "CancelChallan", targetNamespace = "http://TaxManagementSystem/", className = "com.inov8.integration.channel.JSBLB.ETPaymentCollection.client.CancelChallan")
    @ResponseWrapper(localName = "CancelChallanResponse", targetNamespace = "http://TaxManagementSystem/", className = "com.inov8.integration.channel.JSBLB.ETPaymentCollection.client.CancelChallanResponse")
    @WebResult(name = "CancelChallanResult", targetNamespace = "http://TaxManagementSystem/")
    public com.inov8.integration.channel.JSBLB.ETPaymentCollection.client.ChallanDetail cancelChallan(
        @WebParam(name = "ChallanNumber", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String challanNumber,
        @WebParam(name = "VehicleRegistrationNumber", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String vehicleRegistrationNumber,
        @WebParam(name = "CustomerMobileNumber", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String customerMobileNumber,
        @WebParam(name = "ChallanTotalAmount", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String challanTotalAmount,
        @WebParam(name = "ChallanStatus", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String challanStatus,
        @WebParam(name = "BankMnemonic", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String bankMnemonic,
        @WebParam(name = "Cancel_authId", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String cancelAuthId,
        @WebParam(name = "Cancel_TranDate", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String cancelTranDate,
        @WebParam(name = "Cancel_TranTime", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String cancelTranTime
    );

    @WebMethod(operationName = "GenerateChallan", action = "http://TaxManagementSystem/GenerateChallan")
    @RequestWrapper(localName = "GenerateChallan", targetNamespace = "http://TaxManagementSystem/", className = "com.inov8.integration.channel.JSBLB.ETPaymentCollection.client.GenerateChallan")
    @ResponseWrapper(localName = "GenerateChallanResponse", targetNamespace = "http://TaxManagementSystem/", className = "com.inov8.integration.channel.JSBLB.ETPaymentCollection.client.GenerateChallanResponse")
    @WebResult(name = "GenerateChallanResult", targetNamespace = "http://TaxManagementSystem/")
    public com.inov8.integration.channel.JSBLB.ETPaymentCollection.client.ChallanDetail generateChallan(
        @WebParam(name = "AssesementNumber", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String assesementNumber,
        @WebParam(name = "VehicleRegistrationNumber", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String vehicleRegistrationNumber,
        @WebParam(name = "CustomerMobileNumber", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String customerMobileNumber,
        @WebParam(name = "AssesementTotalAmount", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String assesementTotalAmount,
        @WebParam(name = "ChallanStatus", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String challanStatus,
        @WebParam(name = "BankMnemonic", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String bankMnemonic,
        @WebParam(name = "authId", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String authId,
        @WebParam(name = "TranDate", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String tranDate,
        @WebParam(name = "TranTime", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String tranTime
    );

    @WebMethod(operationName = "GetChallanStatus", action = "http://TaxManagementSystem/GetChallanStatus")
    @RequestWrapper(localName = "GetChallanStatus", targetNamespace = "http://TaxManagementSystem/", className = "com.inov8.integration.channel.JSBLB.ETPaymentCollection.client.GetChallanStatus")
    @ResponseWrapper(localName = "GetChallanStatusResponse", targetNamespace = "http://TaxManagementSystem/", className = "com.inov8.integration.channel.JSBLB.ETPaymentCollection.client.GetChallanStatusResponse")
    @WebResult(name = "GetChallanStatusResult", targetNamespace = "http://TaxManagementSystem/")
    public com.inov8.integration.channel.JSBLB.ETPaymentCollection.client.ChallanDetail getChallanStatus(
        @WebParam(name = "ChallanNumber", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String challanNumber,
        @WebParam(name = "VehicleRegistrationNumber", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String vehicleRegistrationNumber,
        @WebParam(name = "BankMnemonic", targetNamespace = "http://TaxManagementSystem/")
        java.lang.String bankMnemonic
    );
}
