package com.inov8.integration.channel.JSBLB.ETPaymentCollection.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-10-27T21:38:00.111+05:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "TaxInquiry", 
                  wsdlLocation = "file:et.wsdl",
                  targetNamespace = "http://TaxManagementSystem/") 
public class TaxInquiry extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://TaxManagementSystem/", "TaxInquiry");
    public final static QName TaxInquirySoap12 = new QName("http://TaxManagementSystem/", "TaxInquirySoap12");
    public final static QName TaxInquirySoap = new QName("http://TaxManagementSystem/", "TaxInquirySoap");
    static {
        URL url = null;
        try {
            url = new URL("file:et.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TaxInquiry.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:et.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TaxInquiry(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TaxInquiry(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaxInquiry() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TaxInquiry(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TaxInquiry(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TaxInquiry(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TaxInquirySoap
     */
    @WebEndpoint(name = "TaxInquirySoap12")
    public TaxInquirySoap getTaxInquirySoap12() {
        return super.getPort(TaxInquirySoap12, TaxInquirySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaxInquirySoap
     */
    @WebEndpoint(name = "TaxInquirySoap12")
    public TaxInquirySoap getTaxInquirySoap12(WebServiceFeature... features) {
        return super.getPort(TaxInquirySoap12, TaxInquirySoap.class, features);
    }


    /**
     *
     * @return
     *     returns TaxInquirySoap
     */
    @WebEndpoint(name = "TaxInquirySoap")
    public TaxInquirySoap getTaxInquirySoap() {
        return super.getPort(TaxInquirySoap, TaxInquirySoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaxInquirySoap
     */
    @WebEndpoint(name = "TaxInquirySoap")
    public TaxInquirySoap getTaxInquirySoap(WebServiceFeature... features) {
        return super.getPort(TaxInquirySoap, TaxInquirySoap.class, features);
    }

}
