package com.inov8.integration.m3.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
public interface ServiceSoap {

	/**
	 * 
	 * @param sMobile
	 * @param sMsg
	 * @param sPassword
	 * @param sUserId
	 * @param sMsgHeader
	 * @param sMsgId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SendSMS", action = "http://tempuri.org/SendSMS")
	@WebResult(name = "SendSMSResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SendSMS", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.m3.client.SendSMS")
	@ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.m3.client.SendSMSResponse")
	public String sendSMS(
			@WebParam(name = "sUserId", targetNamespace = "http://tempuri.org/") String sUserId,
			@WebParam(name = "sPassword", targetNamespace = "http://tempuri.org/") String sPassword,
			@WebParam(name = "sMobile", targetNamespace = "http://tempuri.org/") String sMobile,
			@WebParam(name = "sMsgId", targetNamespace = "http://tempuri.org/") String sMsgId,
			@WebParam(name = "sMsg", targetNamespace = "http://tempuri.org/") String sMsg,
			@WebParam(name = "sMsgHeader", targetNamespace = "http://tempuri.org/") String sMsgHeader);

	/**
	 * 
	 * @param sMobile
	 * @param sMsg
	 * @param sPassword
	 * @param sUserId
	 * @param sMsgHeader
	 * @param sMsgId
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SendSMSUniCode", action = "http://tempuri.org/SendSMSUniCode")
	@WebResult(name = "SendSMSUniCodeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SendSMSUniCode", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.m3.client.SendSMSUniCode")
	@ResponseWrapper(localName = "SendSMSUniCodeResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.m3.client.SendSMSUniCodeResponse")
	public String sendSMSUniCode(
			@WebParam(name = "sUserId", targetNamespace = "http://tempuri.org/") String sUserId,
			@WebParam(name = "sPassword", targetNamespace = "http://tempuri.org/") String sPassword,
			@WebParam(name = "sMobile", targetNamespace = "http://tempuri.org/") String sMobile,
			@WebParam(name = "sMsgId", targetNamespace = "http://tempuri.org/") String sMsgId,
			@WebParam(name = "sMsg", targetNamespace = "http://tempuri.org/") String sMsg,
			@WebParam(name = "sMsgHeader", targetNamespace = "http://tempuri.org/") String sMsgHeader);

}
