package com.inov8.integration.channel.vrg.echallan.service;



import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2018-02-14T18:21:38.524+05:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace ="http://tempuri.org/", name = "ProcessEchallanSoap")
public interface ProcessEchallanSoap {


    @WebMethod(operationName = "BillPayment", action = "http://tempuri.org/BillPayment")
    @RequestWrapper(localName = "BillPayment", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.channel.vrg.echallan.service.BillPayment")
    @ResponseWrapper(localName = "BillPaymentResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.channel.vrg.echallan.service.BillPaymentResponse")
    @WebResult(name = "BillPaymentResult", targetNamespace = "http://tempuri.org/")
    public String billPayment(
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "consumerNumber", targetNamespace = "http://tempuri.org/")
                    String consumerNumber,
            @WebParam(name = "authId", targetNamespace = "http://tempuri.org/")
                    String authId,
            @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
                    String amount,
            @WebParam(name = "tranDate", targetNamespace = "http://tempuri.org/")
                    String tranDate,
            @WebParam(name = "tranTime", targetNamespace = "http://tempuri.org/")
                    String tranTime,
            @WebParam(name = "bankMnemonic", targetNamespace = "http://tempuri.org/")
                    String bankMnemonic,
            @WebParam(name = "reserved", targetNamespace = "http://tempuri.org/")
                    String reserved
    );

    @WebMethod(operationName = "BillInquiry", action = "http://tempuri.org/BillInquiry")
    @RequestWrapper(localName = "BillInquiry", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.channel.vrg.echallan.service.BillInquiry")
    @ResponseWrapper(localName = "BillInquiryResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.channel.vrg.echallan.service.BillInquiryResponse")
    @WebResult(name = "BillInquiryResult", targetNamespace = "http://tempuri.org/")
    public String billInquiry(
            @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
                    String password,
            @WebParam(name = "consumerNumber", targetNamespace = "http://tempuri.org/")
                    String consumerNumber,
            @WebParam(name = "bankMnemonic", targetNamespace = "http://tempuri.org/")
                    String bankMnemonic,
            @WebParam(name = "reserved", targetNamespace = "http://tempuri.org/")
                    String reserved
    );
}
