package com.inov8.microbank.cardconfiguration.common;

public interface CardConstantsInterface {

    String KEY_DEBITCARD_EXPORT_FILE_SIZE = "DebitCard.ExportFileSize";

    Integer KEY_BLB_MOBILE_NUMBER_LENGTH = 11;
    Integer KEY_DEBIT_CARD_NUMBER_LENGTH = 16;

    Long CARD_STATUS_ACTIVE		= 1L;
    Long CARD_STATUS_PENDING	= 2L;
    Long CARD_STATUS_REJECTED = 3L;
    Long CARD_STATUS_APPROVED = 4L;
    Long CARD_STATUS_BLOCKED = 5L;
    Long CARD_STATUS_HOT	= 6L;
    Long CARD_STATUS_DE_ACTIVATED = 7L;
    Long CARD_STATUS_IN_PROCESS = 8L;
    Long CARD_STATUS_INTITATED = 9L;

    Long CARD_STATE_HOT		= 1L;
    Long CARD_STATE_WARM		= 2L;
    Long CARD_STATE_COLD		= 3L;

    String CARD_MIDDLEWARE_STATUS_HOT		= "01";
    String CARD_MIDDLEWARE_STATUS_WARM		= "02";
    String CARD_MIDDLEWARE_STATUS_COLD		= "00";

    String DEBIT_CARD_CUST_TYPE_CODE = "6000";

    String DEBIT_CARD_BRANCH_CODE_ONE = "9522 ";
    String DEBIT_CARD_BRANCH_CODE_TWO = "9523 ";
    String DEBIT_CARD_BRANCH_CODE_THREE = "9526";

    String DEBIT_CARD_SEGMENT_CODE = "9000";

    String DEBIT_CARD_AC_TYPE_CODE_ONE = "1008";
    String DEBIT_CARD_AC_TYPE_CODE_TWO = "1009";
    String DEBIT_CARD_AC_TYPE_CODE_THREE = "1011";

    String DEBIT_CARD_TYPE_CODE = "25";

    String DEBIT_CARD_PROD_CODE = "2";

    String DEBIT_CARD_ONLINE_RQST_TYPE_CODE = "2";

    Long CARD_FEE_TYPE_ISSUANCE = 1L;
    Long CARD_FEE_TYPE_RE_ISSUANCE = 2L;
    Long CARD_FEE_TYPE_ANNUAL = 3L;
    Long ATM_BALANCE_INQUIRY_OFF_US = 4L;
    Long INTERNATIONAL_ATM_BALANCE_INQUIRY_OFF_US = 7L;

}
