package com.inov8.integration.channel.M3tech.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2022-06-07T11:46:16.918+05:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WebService_4_0Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebService40Soap {

    @WebMethod(operationName = "SendSMS", action = "http://tempuri.org/SendSMS")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.channel.M3tech.client.SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.channel.M3tech.client.SendSMSResponse")
    @WebResult(name = "SendSMSResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSMS(
        @WebParam(name = "UserId", targetNamespace = "http://tempuri.org/")
        java.lang.String userId,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(name = "MobileNo", targetNamespace = "http://tempuri.org/")
        java.lang.String mobileNo,
        @WebParam(name = "MsgId", targetNamespace = "http://tempuri.org/")
        java.lang.String msgId,
        @WebParam(name = "SMS", targetNamespace = "http://tempuri.org/")
        java.lang.String sms,
        @WebParam(name = "MsgHeader", targetNamespace = "http://tempuri.org/")
        java.lang.String msgHeader,
        @WebParam(name = "SMSType", targetNamespace = "http://tempuri.org/")
        java.lang.String smsType,
        @WebParam(name = "HandsetPort", targetNamespace = "http://tempuri.org/")
        java.lang.String handsetPort,
        @WebParam(name = "SMSChannel", targetNamespace = "http://tempuri.org/")
        java.lang.String smsChannel,
        @WebParam(name = "Telco", targetNamespace = "http://tempuri.org/")
        java.lang.String telco
    );
}
