package com.inov8.integration.channel.M3tech.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2022-06-07T11:46:16.918+05:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "WebService_4_0HttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WebService40HttpPost {

    @WebMethod(operationName = "SendSMS")
    @WebResult(name = "string", targetNamespace = "http://tempuri.org/", partName = "Body")
    public java.lang.String sendSMS(
        @WebParam(partName = "UserId", name = "UserId", targetNamespace = "http://tempuri.org/")
        java.lang.String userId,
        @WebParam(partName = "Password", name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password,
        @WebParam(partName = "MobileNo", name = "MobileNo", targetNamespace = "http://tempuri.org/")
        java.lang.String mobileNo,
        @WebParam(partName = "MsgId", name = "MsgId", targetNamespace = "http://tempuri.org/")
        java.lang.String msgId,
        @WebParam(partName = "SMS", name = "SMS", targetNamespace = "http://tempuri.org/")
        java.lang.String sms,
        @WebParam(partName = "MsgHeader", name = "MsgHeader", targetNamespace = "http://tempuri.org/")
        java.lang.String msgHeader,
        @WebParam(partName = "SMSType", name = "SMSType", targetNamespace = "http://tempuri.org/")
        java.lang.String smsType,
        @WebParam(partName = "HandsetPort", name = "HandsetPort", targetNamespace = "http://tempuri.org/")
        java.lang.String handsetPort,
        @WebParam(partName = "SMSChannel", name = "SMSChannel", targetNamespace = "http://tempuri.org/")
        java.lang.String smsChannel,
        @WebParam(partName = "Telco", name = "Telco", targetNamespace = "http://tempuri.org/")
        java.lang.String telco
    );
}
