package com.inov8.integration.middleware.translitration.TacitService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2017-10-18T15:11:27.842+05:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://translator.tecthis/", name = "Service1Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface Service1Soap {

    @WebMethod(operationName = "UtoEService", action = "http://translator.tecthis/UtoEService")
    @RequestWrapper(localName = "UtoEService", targetNamespace = "http://translator.tecthis/", className = "com.inov8.integration.middleware.translitration.TacitService.UtoEService")
    @ResponseWrapper(localName = "UtoEServiceResponse", targetNamespace = "http://translator.tecthis/", className = "com.inov8.integration.middleware.translitration.TacitService.UtoEServiceResponse")
    @WebResult(name = "UtoEServiceResult", targetNamespace = "http://translator.tecthis/")
    public String utoEService(
            @WebParam(name = "input_req", targetNamespace = "http://translator.tecthis/")
                    String inputReq
    );

    @WebMethod(operationName = "TestFunc", action = "http://translator.tecthis/TestFunc")
    @RequestWrapper(localName = "TestFunc", targetNamespace = "http://translator.tecthis/", className = "com.inov8.integration.middleware.translitration.TacitService.TestFunc")
    @ResponseWrapper(localName = "TestFuncResponse", targetNamespace = "http://translator.tecthis/", className = "com.inov8.integration.middleware.translitration.TacitService.TestFuncResponse")
    @WebResult(name = "TestFuncResult", targetNamespace = "http://translator.tecthis/")
    public String testFunc(
            @WebParam(name = "a", targetNamespace = "http://translator.tecthis/")
                    String a
    );
}
