package com.inov8.integration.middleware.translitration.TacitService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2017-10-18T15:11:27.893+05:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://translator.tecthis/", name = "Service1HttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Service1HttpGet {

    @WebMethod(operationName = "UtoEService")
    @WebResult(name = "string", targetNamespace = "http://translator.tecthis/", partName = "Body")
    public String utoEService(
            @WebParam(partName = "input_req", name = "input_req", targetNamespace = "http://translator.tecthis/")
                    String inputReq
    );

    @WebMethod(operationName = "TestFunc")
    @WebResult(name = "string", targetNamespace = "http://translator.tecthis/", partName = "Body")
    public String testFunc(
            @WebParam(partName = "a", name = "a", targetNamespace = "http://translator.tecthis/")
                    String a
    );
}
