
package com.inov8.integration.middleware.easypay;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-01-29T12:13:38.933+05:00
 * Generated source version: 3.1.3
 * 
 */
public final class IPartnerBusinessService_PartnerBusinessServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://transaction.partner.pg.systems.com/", "PartnerBusinessService");

    private IPartnerBusinessService_PartnerBusinessServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PartnerBusinessService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PartnerBusinessService ss = new PartnerBusinessService(wsdlURL, SERVICE_NAME);
        IPartnerBusinessService port = ss.getPartnerBusinessServicePort();  
        
        {
        System.out.println("Invoking initiateCCTransaction...");
        com.inov8.integration.middleware.easypay.InitiateCCTransactionRequestType _initiateCCTransaction_parameters1 = null;
        com.inov8.integration.middleware.easypay.InitiateCCTransactionResponseType _initiateCCTransaction__return = port.initiateCCTransaction(_initiateCCTransaction_parameters1);
        System.out.println("initiateCCTransaction.result=" + _initiateCCTransaction__return);


        }
        {
        System.out.println("Invoking initiateTransaction...");
        com.inov8.integration.middleware.easypay.InitiateTransactionRequestType _initiateTransaction_parameters1 = null;
        com.inov8.integration.middleware.easypay.InitiateTransactionResponseType _initiateTransaction__return = port.initiateTransaction(_initiateTransaction_parameters1);
        System.out.println("initiateTransaction.result=" + _initiateTransaction__return);


        }
        {
        System.out.println("Invoking inquireTransaction...");
        com.inov8.integration.middleware.easypay.InquireTransactionRequestType _inquireTransaction_parameters1 = null;
        com.inov8.integration.middleware.easypay.InquireTransactionResponseType _inquireTransaction__return = port.inquireTransaction(_inquireTransaction_parameters1);
        System.out.println("inquireTransaction.result=" + _inquireTransaction__return);


        }

        System.exit(0);
    }

}
