package com.inov8.integration.middleware.easypay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2016-01-29T12:13:39.337+05:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://transaction.partner.pg.systems.com/", name = "IPartnerBusinessService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IPartnerBusinessService {

    @WebMethod
    @WebResult(name = "initiateCCTransactionResponseType", targetNamespace = "http://dto.transaction.partner.pg.systems.com/", partName = "parameters1")
    public InitiateCCTransactionResponseType initiateCCTransaction(
        @WebParam(partName = "parameters1", name = "initiateCCTransactionRequestType", targetNamespace = "http://dto.transaction.partner.pg.systems.com/")
        InitiateCCTransactionRequestType parameters1
    );

    @WebMethod
    @WebResult(name = "initiateTransactionResponseType", targetNamespace = "http://dto.transaction.partner.pg.systems.com/", partName = "parameters1")
    public InitiateTransactionResponseType initiateTransaction(
        @WebParam(partName = "parameters1", name = "initiateTransactionRequestType", targetNamespace = "http://dto.transaction.partner.pg.systems.com/")
        InitiateTransactionRequestType parameters1
    );

    @WebMethod
    @WebResult(name = "inquireTransactionResponseType", targetNamespace = "http://dto.transaction.partner.pg.systems.com/", partName = "parameters1")
    public InquireTransactionResponseType inquireTransaction(
        @WebParam(partName = "parameters1", name = "inquireTransactionRequestType", targetNamespace = "http://dto.transaction.partner.pg.systems.com/")
        InquireTransactionRequestType parameters1
    );
}
