package com.inov8.integration.middleware.enums;

public enum ISO8583FieldEnum {
    // @formatter:off
    PAN(2),
    PROCESSING_CODE(3),
    TRANSACTION_AMOUNT(4),
    SETTLEMENT_AMOUNT(5),
    TRANSACTION_DATE(7),
        SETTLEMENT_CONVERSION_RATE(9),
    SYSTEMS_TRACE_NO(11),
    TIME_LOCAL_TRANSACTION(12),
    DATE_LOCAL_TRANSACTION(13),
    DATE_EXPIRATION(14),
    SETTLEMENT_DATE(15),
    CONVERSION_DATE(16),
    MERCHANT_TYPE(18),
    POS_ENTRY_MODE(22),
    NETWORK_IDENTIFIER(24),
    TRANSACTION_AMOUNT_FEE(28),
    SETTLEMENT_AMOUNT_FEE(29),
    SETTLEMENT_AMOUNT_PROCESSING_FEE(31),
    ACQUIRER_IDENTIFICATION(32),
    TRACK_2_DATA(35),
    RRN(37),
    AUTH_ID_RESPONSE(38),
    RESPONSE_CODE(39),
    TERMINAL_ID(41),
    CARD_ACCEPTOR_IDENTIFICATION_CODE(42),
    CARD_ACCEPTOR_NAME_AND_LOCATION(43),
    ADDITIONAL_RESPONSE_DATA(44),
    TRACK_1_DATA(45),
    ADDITIONAL_REQUEST_DATA_PRIVATE(47),
    ADDITIONAL_RESPONSE_DATA_PRIVATE(48),
    Additional_Data(48),
    TRANSACTION_CURRENCY_CODE(49),
    SETTLEMENT_CURRENCY_CODE(50),
    PIN_DATA(52),
    ADDITIONAL_AMOUNT(54),
    NETWORK_MANAGEMENT_CODE(70),
    ORIGINAL_DATA_ELEMENTS(90),
    MESSAGE_SECURITY_CODE(96),
    ACCOUNCT_NO_1(102),
    ACCOUNCT_NO_2(103),
    RECORD_DATA(120),
    PRIVATE_DATA(127);

    // @formatter:on
    private ISO8583FieldEnum(int value) {
        this.value = value;
    }

    private int value;

    public int getValue() {
        return value;
    }
}
