package com.inov8.integration.util.hsm_payshield;

import com.inov8.hsm.controller.IPayShieldSwitchController;
import com.inov8.hsm.dto.PayShieldDTO;
import org.apache.commons.lang.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * Created by inov8 on 9/17/2018.
 */
public class HSMPinCrackerThread extends Thread {

    private static Logger logger = LoggerFactory.getLogger(HSMPinCrackerThread.class.getSimpleName());
    private static IPayShieldSwitchController inov8PayshieldController = null;
    private static IPayShieldSwitchController bankPayshieldController = null;
    private JdbcTemplate jdbcTemplate;
    private String accountInfoId = "";
    private String customerId = "";
    private String pan = "";
    private String pin = "";
    private String pvv = "";

    public HSMPinCrackerThread(JdbcTemplate jdbcTemplate, IPayShieldSwitchController inov8PayshieldController, IPayShieldSwitchController bankPayshieldController) {
        this.jdbcTemplate = jdbcTemplate;
        this.inov8PayshieldController = inov8PayshieldController;
        this.bankPayshieldController = bankPayshieldController;
    }

    public void run() {
        try {
            logger.info(this.getName() + " RUNNING ");
            PayShieldDTO payShieldDTO = new PayShieldDTO();
            int iteration = 0;
            while (iteration <= 9999) {

                String strPIN = StringUtils.leftPad(Integer.toString(iteration), 4, '0');
                // Verifying PIN using Inov8 HSM
                payShieldDTO = verifyPIN_Inov8HSM(pan, strPIN, pvv);
                if (payShieldDTO.getResponseCode().equals("00")) {
                    logger.info(this.getName() + " PIN verified by Inov8");
                    // Generating PIN & PVV using bank HSM
                    payShieldDTO = generateUserPIN(pan, strPIN);
                    if (payShieldDTO.getResponseCode().equals("00")) {
                        logger.info(this.getName() + " PIN generated by Bank");
                        payShieldDTO = verifyPIN_BankHSM(pan, strPIN, payShieldDTO.getPVV());
                        if (payShieldDTO.getResponseCode().equals("00")) {
                            logger.info(this.getName() + " PIN verified by Bank");
                            jdbcTemplate.update(" update account_info_temp set pvv = ?, pin_status = 'updated' where account_info_id = ? and customer_id = ? and pan = ? ", payShieldDTO.getPVV(), accountInfoId, customerId, pan);
                            logger.info(this.getName() + " Updated PVV in database..");
                        }
                    }
                    break;
                } else {
                    iteration++;
                }
            }
        } catch (Exception ex) {
            logger.info("Exception occurred in " + this.getName());
            logger.error(this.getName(), ex);
        }
        logger.info(this.getName() + " ENDING ");
    }

    public PayShieldDTO verifyPIN_Inov8HSM(String PAN, String PIN, String PVV) throws Exception {
        PayShieldDTO payShieldDTO = new PayShieldDTO();
        payShieldDTO.setPAN(PAN);
        payShieldDTO.setPIN(PIN);
        payShieldDTO.setPVV(PVV);
        payShieldDTO = (PayShieldDTO) inov8PayshieldController.verifyPIN(payShieldDTO);
        return payShieldDTO;
    }

    public PayShieldDTO generateUserPIN(String PAN, String PIN) throws Exception {
        PayShieldDTO payShieldDTO = new PayShieldDTO();
        payShieldDTO.setPAN(PAN);
        payShieldDTO.setPIN(PIN);

        payShieldDTO = (PayShieldDTO) bankPayshieldController.generateUserPIN(payShieldDTO);
        return payShieldDTO;
    }

    public PayShieldDTO verifyPIN_BankHSM(String PAN, String PIN, String PVV) throws Exception {
        PayShieldDTO payShieldDTO = new PayShieldDTO();
        payShieldDTO.setPAN(PAN);
        payShieldDTO.setPIN(PIN);
        payShieldDTO.setPVV(PVV);
        payShieldDTO = (PayShieldDTO) bankPayshieldController.verifyPIN(payShieldDTO);
        return payShieldDTO;
    }

    public String getAccountInfoId() {
        return accountInfoId;
    }

    public void setAccountInfoId(String accountInfoId) {
        this.accountInfoId = accountInfoId;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public String getPan() {
        return pan;
    }

    public void setPan(String pan) {
        this.pan = pan;
    }

    public String getPin() {
        return pin;
    }

    public void setPin(String pin) {
        this.pin = pin;
    }

    public String getPvv() {
        return pvv;
    }

    public void setPvv(String pvv) {
        this.pvv = pvv;
    }
}
