package com.inov8.microbank.server.service.orphantransaction;

import com.inov8.framework.common.exception.FrameworkCheckedException;
import com.inov8.microbank.common.exception.WorkFlowException;
import com.inov8.microbank.common.model.StakeholderBankInfoModel;
import com.inov8.microbank.common.model.TransactionDetailMasterModel;
import com.inov8.microbank.common.model.TransactionModel;

public interface OrphanTransactionManager {
	
	public boolean reverseOrphanTransaction(TransactionModel transaction,StakeholderBankInfoModel olaSundaryAccount, Double txAmount) throws Exception;
	public boolean reverseC2COrphanTransaction(TransactionDetailMasterModel transactionDetailMasterModel, TransactionModel transaction,StakeholderBankInfoModel olaSundaryAccount, StakeholderBankInfoModel olaUnclaimedSundaryAccount) throws FrameworkCheckedException, WorkFlowException;
	public boolean reverseBulkPaymentOrphanTransaction(TransactionModel transaction,StakeholderBankInfoModel olaSundaryAccount, StakeholderBankInfoModel olaUnclaimedSundaryAccount) throws FrameworkCheckedException, WorkFlowException;
	public boolean makeTransactionsUnclaimed(TransactionModel transaction,StakeholderBankInfoModel olaSundaryAccount, StakeholderBankInfoModel olaUnclaimedSundaryAccount) throws FrameworkCheckedException, WorkFlowException;
	
}
