package com.inov8.microbank.server.webserviceclient.ivr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ivrwebservice", targetNamespace = "http://server.ws.microbank.inov8.com/")
public interface IvrWebService {

	/**
	 * 
	 * @param ivrRequestDTO
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "handleRequest", targetNamespace = "http://server.ws.microbank.inov8.com/", className = "com.inov8.microbank.server.webserviceclient.ivr.HandleRequest")
	@ResponseWrapper(localName = "handleRequestResponse", targetNamespace = "http://server.ws.microbank.inov8.com/", className = "com.inov8.microbank.server.webserviceclient.ivr.HandleRequestResponse")
	public String handleRequest(
			@WebParam(name = "ivrRequestDTO", targetNamespace = "") IvrRequestDTO ivrRequestDTO);

}
