package com.inov8.integration.middleware.prisim;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-22T15:52:22.455+05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "ISBLMobileAppService")
@XmlSeeAlso({ObjectFactory.class})
public interface ISBLMobileAppService {

    @WebMethod(operationName = "ForgotLoginID", action = "http://tempuri.org/ISBLMobileAppService/ForgotLoginID")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/ForgotLoginID", output = "http://tempuri.org/ISBLMobileAppService/ForgotLoginIDResponse")
    @RequestWrapper(localName = "ForgotLoginID", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ForgotLoginID")
    @ResponseWrapper(localName = "ForgotLoginIDResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ForgotLoginIDResponse")
    @WebResult(name = "ForgotLoginIDResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.ForgotIdOutputParams forgotLoginID(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "EmailAddress", targetNamespace = "http://tempuri.org/")
        java.lang.String emailAddress
    );

    @WebMethod(operationName = "GetCustomer", action = "http://tempuri.org/ISBLMobileAppService/GetCustomer")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GetCustomer", output = "http://tempuri.org/ISBLMobileAppService/GetCustomerResponse")
    @RequestWrapper(localName = "GetCustomer", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetCustomer")
    @ResponseWrapper(localName = "GetCustomerResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetCustomerResponse")
    @WebResult(name = "GetCustomerResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.CustomerRequestOutputParams getCustomer(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "Registration", action = "http://tempuri.org/ISBLMobileAppService/Registration")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/Registration", output = "http://tempuri.org/ISBLMobileAppService/RegistrationResponse")
    @RequestWrapper(localName = "Registration", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.Registration")
    @ResponseWrapper(localName = "RegistrationResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.RegistrationResponse")
    @WebResult(name = "RegistrationResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.RegistrationOutputParams registration(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "Registration", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.Registration2 registration
    );

    @WebMethod(operationName = "GetBillingCompanies", action = "http://tempuri.org/ISBLMobileAppService/GetBillingCompanies")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GetBillingCompanies", output = "http://tempuri.org/ISBLMobileAppService/GetBillingCompaniesResponse")
    @RequestWrapper(localName = "GetBillingCompanies", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetBillingCompanies")
    @ResponseWrapper(localName = "GetBillingCompaniesResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetBillingCompaniesResponse")
    @WebResult(name = "GetBillingCompaniesResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.BillingCompaniesOutputParams getBillingCompanies(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "GenerateOTP", action = "http://tempuri.org/ISBLMobileAppService/GenerateOTP")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GenerateOTP", output = "http://tempuri.org/ISBLMobileAppService/GenerateOTPResponse")
    @RequestWrapper(localName = "GenerateOTP", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GenerateOTP")
    @ResponseWrapper(localName = "GenerateOTPResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GenerateOTPResponse")
    @WebResult(name = "GenerateOTPResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.GenerateOTPOutputParams generateOTP(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "FundTransferSchedule", action = "http://tempuri.org/ISBLMobileAppService/FundTransferSchedule")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/FundTransferSchedule", output = "http://tempuri.org/ISBLMobileAppService/FundTransferScheduleResponse")
    @RequestWrapper(localName = "FundTransferSchedule", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.FundTransferSchedule")
    @ResponseWrapper(localName = "FundTransferScheduleResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.FundTransferScheduleResponse")
    @WebResult(name = "FundTransferScheduleResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.FundTransferScheduleOutputParams fundTransferSchedule(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "CustomerAccount", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.CustomerAccount customerAccount,
        @WebParam(name = "BeneficiaryType", targetNamespace = "http://tempuri.org/")
        java.lang.String beneficiaryType,
        @WebParam(name = "BeneficiaryAccount", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.BeneficiaryAccount beneficiaryAccount,
        @WebParam(name = "PaymentDetailDTO", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.PaymentDetailDTO paymentDetailDTO,
        @WebParam(name = "FinancialPin", targetNamespace = "http://tempuri.org/")
        java.lang.String financialPin
    );

    @WebMethod(operationName = "BlockInternetBanking", action = "http://tempuri.org/ISBLMobileAppService/BlockInternetBanking")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/BlockInternetBanking", output = "http://tempuri.org/ISBLMobileAppService/BlockInternetBankingResponse")
    @RequestWrapper(localName = "BlockInternetBanking", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.BlockInternetBanking")
    @ResponseWrapper(localName = "BlockInternetBankingResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.BlockInternetBankingResponse")
    @WebResult(name = "BlockInternetBankingResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.BlockInternetBankingOutputParams blockInternetBanking(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "GetSecretQuestion", action = "http://tempuri.org/ISBLMobileAppService/GetSecretQuestion")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GetSecretQuestion", output = "http://tempuri.org/ISBLMobileAppService/GetSecretQuestionResponse")
    @RequestWrapper(localName = "GetSecretQuestion", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetSecretQuestion")
    @ResponseWrapper(localName = "GetSecretQuestionResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetSecretQuestionResponse")
    @WebResult(name = "GetSecretQuestionResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.SecretQuestionOutputParams getSecretQuestion(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "GetBeneficiaryRelationships", action = "http://tempuri.org/ISBLMobileAppService/GetBeneficiaryRelationships")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GetBeneficiaryRelationships", output = "http://tempuri.org/ISBLMobileAppService/GetBeneficiaryRelationshipsResponse")
    @RequestWrapper(localName = "GetBeneficiaryRelationships", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetBeneficiaryRelationships")
    @ResponseWrapper(localName = "GetBeneficiaryRelationshipsResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetBeneficiaryRelationshipsResponse")
    @WebResult(name = "GetBeneficiaryRelationshipsResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.BeneficiaryRelationshipOutputParams getBeneficiaryRelationships(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "GetTransactionHistory", action = "http://tempuri.org/ISBLMobileAppService/GetTransactionHistory")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GetTransactionHistory", output = "http://tempuri.org/ISBLMobileAppService/GetTransactionHistoryResponse")
    @RequestWrapper(localName = "GetTransactionHistory", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetTransactionHistory")
    @ResponseWrapper(localName = "GetTransactionHistoryResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetTransactionHistoryResponse")
    @WebResult(name = "GetTransactionHistoryResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.TransactionHistoryOutputParams getTransactionHistory(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "DateRange", targetNamespace = "http://tempuri.org/")
        java.lang.String dateRange,
        @WebParam(name = "TransactionType", targetNamespace = "http://tempuri.org/")
        java.lang.String transactionType
    );

    @WebMethod(operationName = "DeleteScheduleTransaction", action = "http://tempuri.org/ISBLMobileAppService/DeleteScheduleTransaction")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/DeleteScheduleTransaction", output = "http://tempuri.org/ISBLMobileAppService/DeleteScheduleTransactionResponse")
    @RequestWrapper(localName = "DeleteScheduleTransaction", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.DeleteScheduleTransaction")
    @ResponseWrapper(localName = "DeleteScheduleTransactionResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.DeleteScheduleTransactionResponse")
    @WebResult(name = "DeleteScheduleTransactionResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.DeleteScheduleTransactionOutputParams deleteScheduleTransaction(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "TransactionType", targetNamespace = "http://tempuri.org/")
        java.lang.String transactionType,
        @WebParam(name = "BatchId", targetNamespace = "http://tempuri.org/")
        java.lang.String batchId
    );

    @WebMethod(operationName = "GetBankDetails", action = "http://tempuri.org/ISBLMobileAppService/GetBankDetails")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GetBankDetails", output = "http://tempuri.org/ISBLMobileAppService/GetBankDetailsResponse")
    @RequestWrapper(localName = "GetBankDetails", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetBankDetails")
    @ResponseWrapper(localName = "GetBankDetailsResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetBankDetailsResponse")
    @WebResult(name = "GetBankDetailsResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.BankDetailsOutputParams getBankDetails(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "ChangeSecretAnswer", action = "http://tempuri.org/ISBLMobileAppService/ChangeSecretAnswer")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/ChangeSecretAnswer", output = "http://tempuri.org/ISBLMobileAppService/ChangeSecretAnswerResponse")
    @RequestWrapper(localName = "ChangeSecretAnswer", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ChangeSecretAnswer")
    @ResponseWrapper(localName = "ChangeSecretAnswerResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ChangeSecretAnswerResponse")
    @WebResult(name = "ChangeSecretAnswerResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.ChangeSecretAnswerOutputParams changeSecretAnswer(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "OldSecretQuestion", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.SecretQuestion oldSecretQuestion,
        @WebParam(name = "OldSecretAnswer", targetNamespace = "http://tempuri.org/")
        java.lang.String oldSecretAnswer,
        @WebParam(name = "NewSecretQuestion", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.SecretQuestion newSecretQuestion,
        @WebParam(name = "NewSecretAnswer", targetNamespace = "http://tempuri.org/")
        java.lang.String newSecretAnswer
    );

    @WebMethod(operationName = "SetFirstTimeLogin", action = "http://tempuri.org/ISBLMobileAppService/SetFirstTimeLogin")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/SetFirstTimeLogin", output = "http://tempuri.org/ISBLMobileAppService/SetFirstTimeLoginResponse")
    @RequestWrapper(localName = "SetFirstTimeLogin", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.SetFirstTimeLogin")
    @ResponseWrapper(localName = "SetFirstTimeLoginResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.SetFirstTimeLoginResponse")
    @WebResult(name = "SetFirstTimeLoginResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.SetFirstTimeLoginOutputParams setFirstTimeLogin(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "GetPurposes", action = "http://tempuri.org/ISBLMobileAppService/GetPurposes")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GetPurposes", output = "http://tempuri.org/ISBLMobileAppService/GetPurposesResponse")
    @RequestWrapper(localName = "GetPurposes", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetPurposes")
    @ResponseWrapper(localName = "GetPurposesResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetPurposesResponse")
    @WebResult(name = "GetPurposesResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.PurposeOutputParams getPurposes(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "ViewScheduleFundsTransfer", action = "http://tempuri.org/ISBLMobileAppService/ViewScheduleFundsTransfer")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/ViewScheduleFundsTransfer", output = "http://tempuri.org/ISBLMobileAppService/ViewScheduleFundsTransferResponse")
    @RequestWrapper(localName = "ViewScheduleFundsTransfer", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ViewScheduleFundsTransfer")
    @ResponseWrapper(localName = "ViewScheduleFundsTransferResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ViewScheduleFundsTransferResponse")
    @WebResult(name = "ViewScheduleFundsTransferResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.ViewScheduleFundsTransferOutputParams viewScheduleFundsTransfer(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "TransactionType", targetNamespace = "http://tempuri.org/")
        java.lang.String transactionType
    );

    @WebMethod(operationName = "AddBeneficiaryAccount", action = "http://tempuri.org/ISBLMobileAppService/AddBeneficiaryAccount")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/AddBeneficiaryAccount", output = "http://tempuri.org/ISBLMobileAppService/AddBeneficiaryAccountResponse")
    @RequestWrapper(localName = "AddBeneficiaryAccount", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.AddBeneficiaryAccount")
    @ResponseWrapper(localName = "AddBeneficiaryAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.AddBeneficiaryAccountResponse")
    @WebResult(name = "AddBeneficiaryAccountResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.AddBeneficiaryOutputParams addBeneficiaryAccount(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "BeneficiaryAccount", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.BeneficiaryAccount beneficiaryAccount,
        @WebParam(name = "OTP", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.OTP otp,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "GetBeneficiaryAccounts", action = "http://tempuri.org/ISBLMobileAppService/GetBeneficiaryAccounts")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GetBeneficiaryAccounts", output = "http://tempuri.org/ISBLMobileAppService/GetBeneficiaryAccountsResponse")
    @RequestWrapper(localName = "GetBeneficiaryAccounts", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetBeneficiaryAccounts")
    @ResponseWrapper(localName = "GetBeneficiaryAccountsResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetBeneficiaryAccountsResponse")
    @WebResult(name = "GetBeneficiaryAccountsResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.BeneficiaryAccountOutputParams getBeneficiaryAccounts(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "BeneficiaryType", targetNamespace = "http://tempuri.org/")
        java.lang.String beneficiaryType,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "ChangeEmail", action = "http://tempuri.org/ISBLMobileAppService/ChangeEmail")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/ChangeEmail", output = "http://tempuri.org/ISBLMobileAppService/ChangeEmailResponse")
    @RequestWrapper(localName = "ChangeEmail", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ChangeEmail")
    @ResponseWrapper(localName = "ChangeEmailResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ChangeEmailResponse")
    @WebResult(name = "ChangeEmailResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.ChangeEmailOutputParams changeEmail(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "SecretQuestion", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.SecretQuestion secretQuestion,
        @WebParam(name = "SecretAnswer", targetNamespace = "http://tempuri.org/")
        java.lang.String secretAnswer,
        @WebParam(name = "OldEmail", targetNamespace = "http://tempuri.org/")
        java.lang.String oldEmail,
        @WebParam(name = "NewEmail", targetNamespace = "http://tempuri.org/")
        java.lang.String newEmail
    );

    @WebMethod(operationName = "DeleteBillPayee", action = "http://tempuri.org/ISBLMobileAppService/DeleteBillPayee")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/DeleteBillPayee", output = "http://tempuri.org/ISBLMobileAppService/DeleteBillPayeeResponse")
    @RequestWrapper(localName = "DeleteBillPayee", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.DeleteBillPayee")
    @ResponseWrapper(localName = "DeleteBillPayeeResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.DeleteBillPayeeResponse")
    @WebResult(name = "DeleteBillPayeeResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.DeleteBillPayeeOutputParams deleteBillPayee(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "BillPayee", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.BillPayee billPayee,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "GenerateFinancialPIN", action = "http://tempuri.org/ISBLMobileAppService/GenerateFinancialPIN")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GenerateFinancialPIN", output = "http://tempuri.org/ISBLMobileAppService/GenerateFinancialPINResponse")
    @RequestWrapper(localName = "GenerateFinancialPIN", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GenerateFinancialPIN")
    @ResponseWrapper(localName = "GenerateFinancialPINResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GenerateFinancialPINResponse")
    @WebResult(name = "GenerateFinancialPINResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.GenerateFinancialPinOutputParams generateFinancialPIN(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "FinancialPINNature", targetNamespace = "http://tempuri.org/")
        java.lang.String financialPINNature,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "ModifyBeneficiaryAccount", action = "http://tempuri.org/ISBLMobileAppService/ModifyBeneficiaryAccount")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/ModifyBeneficiaryAccount", output = "http://tempuri.org/ISBLMobileAppService/ModifyBeneficiaryAccountResponse")
    @RequestWrapper(localName = "ModifyBeneficiaryAccount", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ModifyBeneficiaryAccount")
    @ResponseWrapper(localName = "ModifyBeneficiaryAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ModifyBeneficiaryAccountResponse")
    @WebResult(name = "ModifyBeneficiaryAccountResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.ModifyBeneficiaryAccountOutputParams modifyBeneficiaryAccount(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "BeneficiaryAccount", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.BeneficiaryAccount beneficiaryAccount,
        @WebParam(name = "OTP", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.OTP otp,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "GetCardStatement", action = "http://tempuri.org/ISBLMobileAppService/GetCardStatement")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GetCardStatement", output = "http://tempuri.org/ISBLMobileAppService/GetCardStatementResponse")
    @RequestWrapper(localName = "GetCardStatement", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetCardStatement")
    @ResponseWrapper(localName = "GetCardStatementResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetCardStatementResponse")
    @WebResult(name = "GetCardStatementResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.CardStatementOutputParams getCardStatement(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "CardStatementFilter", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.CardStatementFilter cardStatementFilter,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "CardNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String cardNumber
    );

    @WebMethod(operationName = "GetLoginHistory", action = "http://tempuri.org/ISBLMobileAppService/GetLoginHistory")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GetLoginHistory", output = "http://tempuri.org/ISBLMobileAppService/GetLoginHistoryResponse")
    @RequestWrapper(localName = "GetLoginHistory", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetLoginHistory")
    @ResponseWrapper(localName = "GetLoginHistoryResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetLoginHistoryResponse")
    @WebResult(name = "GetLoginHistoryResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.LoginHistoryOutputParams getLoginHistory(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "BillPaymentSchedule", action = "http://tempuri.org/ISBLMobileAppService/BillPaymentSchedule")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/BillPaymentSchedule", output = "http://tempuri.org/ISBLMobileAppService/BillPaymentScheduleResponse")
    @RequestWrapper(localName = "BillPaymentSchedule", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.BillPaymentSchedule")
    @ResponseWrapper(localName = "BillPaymentScheduleResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.BillPaymentScheduleResponse")
    @WebResult(name = "BillPaymentScheduleResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.BillPaymentScheduleOutputParams billPaymentSchedule(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "CustomerAccount", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.CustomerAccount customerAccount,
        @WebParam(name = "Payee", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.BillPayee payee,
        @WebParam(name = "PaymentDetailDTO", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.PaymentDetailDTO paymentDetailDTO,
        @WebParam(name = "FinancialPin", targetNamespace = "http://tempuri.org/")
        java.lang.String financialPin
    );

    @WebMethod(operationName = "ExpireFinancialPIN", action = "http://tempuri.org/ISBLMobileAppService/ExpireFinancialPIN")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/ExpireFinancialPIN", output = "http://tempuri.org/ISBLMobileAppService/ExpireFinancialPINResponse")
    @RequestWrapper(localName = "ExpireFinancialPIN", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ExpireFinancialPIN")
    @ResponseWrapper(localName = "ExpireFinancialPINResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ExpireFinancialPINResponse")
    @WebResult(name = "ExpireFinancialPINResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.ExpireFinancialPinOutputParams expireFinancialPIN(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "GetAccountStatement", action = "http://tempuri.org/ISBLMobileAppService/GetAccountStatement")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GetAccountStatement", output = "http://tempuri.org/ISBLMobileAppService/GetAccountStatementResponse")
    @RequestWrapper(localName = "GetAccountStatement", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetAccountStatement")
    @ResponseWrapper(localName = "GetAccountStatementResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetAccountStatementResponse")
    @WebResult(name = "GetAccountStatementResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.AccountStatementOutputParams getAccountStatement(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "AccountStatementFilter", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.AccountStatementFilter accountStatementFilter,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "AccountNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String accountNumber
    );

    @WebMethod(operationName = "DeleteBeneficiaryAccount", action = "http://tempuri.org/ISBLMobileAppService/DeleteBeneficiaryAccount")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/DeleteBeneficiaryAccount", output = "http://tempuri.org/ISBLMobileAppService/DeleteBeneficiaryAccountResponse")
    @RequestWrapper(localName = "DeleteBeneficiaryAccount", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.DeleteBeneficiaryAccount")
    @ResponseWrapper(localName = "DeleteBeneficiaryAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.DeleteBeneficiaryAccountResponse")
    @WebResult(name = "DeleteBeneficiaryAccountResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.DeleteBeneficiaryAccountOutputParams deleteBeneficiaryAccount(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "BeneficiaryAccount", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.BeneficiaryAccount beneficiaryAccount,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "GetBillPayee", action = "http://tempuri.org/ISBLMobileAppService/GetBillPayee")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GetBillPayee", output = "http://tempuri.org/ISBLMobileAppService/GetBillPayeeResponse")
    @RequestWrapper(localName = "GetBillPayee", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetBillPayee")
    @ResponseWrapper(localName = "GetBillPayeeResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetBillPayeeResponse")
    @WebResult(name = "GetBillPayeeResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.BillPayeeOutputParams getBillPayee(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "EditScheduleTransaction", action = "http://tempuri.org/ISBLMobileAppService/EditScheduleTransaction")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/EditScheduleTransaction", output = "http://tempuri.org/ISBLMobileAppService/EditScheduleTransactionResponse")
    @RequestWrapper(localName = "EditScheduleTransaction", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.EditScheduleTransaction")
    @ResponseWrapper(localName = "EditScheduleTransactionResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.EditScheduleTransactionResponse")
    @WebResult(name = "EditScheduleTransactionResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.EditScheduleTransactionOutputParams editScheduleTransaction(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "TransactionType", targetNamespace = "http://tempuri.org/")
        java.lang.String transactionType,
        @WebParam(name = "RecurPattern", targetNamespace = "http://tempuri.org/")
        java.lang.String recurPattern,
        @WebParam(name = "RecurEndType", targetNamespace = "http://tempuri.org/")
        java.lang.String recurEndType,
        @WebParam(name = "StartDate", targetNamespace = "http://tempuri.org/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://tempuri.org/")
        java.lang.String endDate,
        @WebParam(name = "NoOfOccurrence", targetNamespace = "http://tempuri.org/")
        java.lang.String noOfOccurrence,
        @WebParam(name = "BatchId", targetNamespace = "http://tempuri.org/")
        java.lang.String batchId
    );

    @WebMethod(operationName = "AddBillPayee", action = "http://tempuri.org/ISBLMobileAppService/AddBillPayee")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/AddBillPayee", output = "http://tempuri.org/ISBLMobileAppService/AddBillPayeeResponse")
    @RequestWrapper(localName = "AddBillPayee", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.AddBillPayee")
    @ResponseWrapper(localName = "AddBillPayeeResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.AddBillPayeeResponse")
    @WebResult(name = "AddBillPayeeResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.AddBillPayeeOutputParams addBillPayee(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "BillPayee", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.BillPayee billPayee,
        @WebParam(name = "OTP", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.OTP otp,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "GenerateMobilePin", action = "http://tempuri.org/ISBLMobileAppService/GenerateMobilePin")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GenerateMobilePin", output = "http://tempuri.org/ISBLMobileAppService/GenerateMobilePinResponse")
    @RequestWrapper(localName = "GenerateMobilePin", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GenerateMobilePin")
    @ResponseWrapper(localName = "GenerateMobilePinResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GenerateMobilePinResponse")
    @WebResult(name = "GenerateMobilePinResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.GenerateMobilePinOutputParams generateMobilePin(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "AuditLoggging", action = "http://tempuri.org/ISBLMobileAppService/AuditLoggging")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/AuditLoggging", output = "http://tempuri.org/ISBLMobileAppService/AuditLogggingResponse")
    @RequestWrapper(localName = "AuditLoggging", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.AuditLoggging")
    @ResponseWrapper(localName = "AuditLogggingResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.AuditLogggingResponse")
    @WebResult(name = "AuditLogggingResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.AuditLoggingOutputParams auditLoggging(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "TransactionType", targetNamespace = "http://tempuri.org/")
        java.lang.String transactionType,
        @WebParam(name = "AuditLogging", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.AuditLoggingRequest auditLogging
    );

    @WebMethod(operationName = "ViewScheduledBillPayment", action = "http://tempuri.org/ISBLMobileAppService/ViewScheduledBillPayment")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/ViewScheduledBillPayment", output = "http://tempuri.org/ISBLMobileAppService/ViewScheduledBillPaymentResponse")
    @RequestWrapper(localName = "ViewScheduledBillPayment", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ViewScheduledBillPayment")
    @ResponseWrapper(localName = "ViewScheduledBillPaymentResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ViewScheduledBillPaymentResponse")
    @WebResult(name = "ViewScheduledBillPaymentResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.ViewScheduledBillPaymentOutputParams viewScheduledBillPayment(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "VerifyFinancialPIN", action = "http://tempuri.org/ISBLMobileAppService/VerifyFinancialPIN")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/VerifyFinancialPIN", output = "http://tempuri.org/ISBLMobileAppService/VerifyFinancialPINResponse")
    @RequestWrapper(localName = "VerifyFinancialPIN", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.VerifyFinancialPIN")
    @ResponseWrapper(localName = "VerifyFinancialPINResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.VerifyFinancialPINResponse")
    @WebResult(name = "VerifyFinancialPINResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.VerifyFinancialPinOutputParams verifyFinancialPIN(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "FinancialPIN", targetNamespace = "http://tempuri.org/")
        java.lang.String financialPIN,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "GetBillingCompanyTypes", action = "http://tempuri.org/ISBLMobileAppService/GetBillingCompanyTypes")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/GetBillingCompanyTypes", output = "http://tempuri.org/ISBLMobileAppService/GetBillingCompanyTypesResponse")
    @RequestWrapper(localName = "GetBillingCompanyTypes", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetBillingCompanyTypes")
    @ResponseWrapper(localName = "GetBillingCompanyTypesResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.GetBillingCompanyTypesResponse")
    @WebResult(name = "GetBillingCompanyTypesResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.BillingCompanyTypeOutputParams getBillingCompanyTypes(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName
    );

    @WebMethod(operationName = "ForgotSecretAnswer", action = "http://tempuri.org/ISBLMobileAppService/ForgotSecretAnswer")
    @Action(input = "http://tempuri.org/ISBLMobileAppService/ForgotSecretAnswer", output = "http://tempuri.org/ISBLMobileAppService/ForgotSecretAnswerResponse")
    @RequestWrapper(localName = "ForgotSecretAnswer", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ForgotSecretAnswer")
    @ResponseWrapper(localName = "ForgotSecretAnswerResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.prisim.ForgotSecretAnswerResponse")
    @WebResult(name = "ForgotSecretAnswerResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.prisim.ForgotSecretAnswerOutputParams forgotSecretAnswer(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.InputHeader inputHeader,
        @WebParam(name = "ChannelUserIdentifier", targetNamespace = "http://tempuri.org/")
        java.lang.String channelUserIdentifier,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "NewSecretQuestion", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.prisim.SecretQuestion newSecretQuestion,
        @WebParam(name = "NewSecretAnswer", targetNamespace = "http://tempuri.org/")
        java.lang.String newSecretAnswer,
        @WebParam(name = "MobilePin", targetNamespace = "http://tempuri.org/")
        java.lang.String mobilePin
    );
}
