
package com.inov8.integration.middleware.prisim;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-22T15:52:21.688+05:00
 * Generated source version: 3.1.6
 * 
 */
public final class ISBLMobileAppService_BasicHttpBindingISBLMobileAppService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "SBLMobileAppService");

    private ISBLMobileAppService_BasicHttpBindingISBLMobileAppService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SBLMobileAppService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SBLMobileAppService ss = new SBLMobileAppService(wsdlURL, SERVICE_NAME);
        ISBLMobileAppService port = ss.getBasicHttpBindingISBLMobileAppService();  
        
        {
        System.out.println("Invoking forgotLoginID...");
        com.inov8.integration.middleware.prisim.InputHeader _forgotLoginID_inputHeader = null;
        java.lang.String _forgotLoginID_channelUserIdentifier = "";
        java.lang.String _forgotLoginID_emailAddress = "";
        com.inov8.integration.middleware.prisim.ForgotIdOutputParams _forgotLoginID__return = port.forgotLoginID(_forgotLoginID_inputHeader, _forgotLoginID_channelUserIdentifier, _forgotLoginID_emailAddress);
        System.out.println("forgotLoginID.result=" + _forgotLoginID__return);


        }
        {
        System.out.println("Invoking getCustomer...");
        com.inov8.integration.middleware.prisim.InputHeader _getCustomer_inputHeader = null;
        java.lang.String _getCustomer_customerUserName = "";
        com.inov8.integration.middleware.prisim.CustomerRequestOutputParams _getCustomer__return = port.getCustomer(_getCustomer_inputHeader, _getCustomer_customerUserName);
        System.out.println("getCustomer.result=" + _getCustomer__return);


        }
        {
        System.out.println("Invoking registration...");
        com.inov8.integration.middleware.prisim.InputHeader _registration_inputHeader = null;
        com.inov8.integration.middleware.prisim.Registration2 _registration_registration = null;
        com.inov8.integration.middleware.prisim.RegistrationOutputParams _registration__return = port.registration(_registration_inputHeader, _registration_registration);
        System.out.println("registration.result=" + _registration__return);


        }
        {
        System.out.println("Invoking getBillingCompanies...");
        com.inov8.integration.middleware.prisim.InputHeader _getBillingCompanies_inputHeader = null;
        java.lang.String _getBillingCompanies_channelUserIdentifier = "";
        java.lang.String _getBillingCompanies_customerUserName = "";
        com.inov8.integration.middleware.prisim.BillingCompaniesOutputParams _getBillingCompanies__return = port.getBillingCompanies(_getBillingCompanies_inputHeader, _getBillingCompanies_channelUserIdentifier, _getBillingCompanies_customerUserName);
        System.out.println("getBillingCompanies.result=" + _getBillingCompanies__return);


        }
        {
        System.out.println("Invoking generateOTP...");
        com.inov8.integration.middleware.prisim.InputHeader _generateOTP_inputHeader = null;
        java.lang.String _generateOTP_channelUserIdentifier = "";
        java.lang.String _generateOTP_customerUserName = "";
        com.inov8.integration.middleware.prisim.GenerateOTPOutputParams _generateOTP__return = port.generateOTP(_generateOTP_inputHeader, _generateOTP_channelUserIdentifier, _generateOTP_customerUserName);
        System.out.println("generateOTP.result=" + _generateOTP__return);


        }
        {
        System.out.println("Invoking fundTransferSchedule...");
        com.inov8.integration.middleware.prisim.InputHeader _fundTransferSchedule_inputHeader = null;
        java.lang.String _fundTransferSchedule_channelUserIdentifier = "";
        java.lang.String _fundTransferSchedule_customerUserName = "";
        com.inov8.integration.middleware.prisim.CustomerAccount _fundTransferSchedule_customerAccount = null;
        java.lang.String _fundTransferSchedule_beneficiaryType = "";
        com.inov8.integration.middleware.prisim.BeneficiaryAccount _fundTransferSchedule_beneficiaryAccount = null;
        com.inov8.integration.middleware.prisim.PaymentDetailDTO _fundTransferSchedule_paymentDetailDTO = null;
        java.lang.String _fundTransferSchedule_financialPin = "";
        com.inov8.integration.middleware.prisim.FundTransferScheduleOutputParams _fundTransferSchedule__return = port.fundTransferSchedule(_fundTransferSchedule_inputHeader, _fundTransferSchedule_channelUserIdentifier, _fundTransferSchedule_customerUserName, _fundTransferSchedule_customerAccount, _fundTransferSchedule_beneficiaryType, _fundTransferSchedule_beneficiaryAccount, _fundTransferSchedule_paymentDetailDTO, _fundTransferSchedule_financialPin);
        System.out.println("fundTransferSchedule.result=" + _fundTransferSchedule__return);


        }
        {
        System.out.println("Invoking blockInternetBanking...");
        com.inov8.integration.middleware.prisim.InputHeader _blockInternetBanking_inputHeader = null;
        java.lang.String _blockInternetBanking_channelUserIdentifier = "";
        java.lang.String _blockInternetBanking_customerUserName = "";
        com.inov8.integration.middleware.prisim.BlockInternetBankingOutputParams _blockInternetBanking__return = port.blockInternetBanking(_blockInternetBanking_inputHeader, _blockInternetBanking_channelUserIdentifier, _blockInternetBanking_customerUserName);
        System.out.println("blockInternetBanking.result=" + _blockInternetBanking__return);


        }
        {
        System.out.println("Invoking getSecretQuestion...");
        com.inov8.integration.middleware.prisim.InputHeader _getSecretQuestion_inputHeader = null;
        java.lang.String _getSecretQuestion_channelUserIdentifier = "";
        java.lang.String _getSecretQuestion_customerUserName = "";
        com.inov8.integration.middleware.prisim.SecretQuestionOutputParams _getSecretQuestion__return = port.getSecretQuestion(_getSecretQuestion_inputHeader, _getSecretQuestion_channelUserIdentifier, _getSecretQuestion_customerUserName);
        System.out.println("getSecretQuestion.result=" + _getSecretQuestion__return);


        }
        {
        System.out.println("Invoking getBeneficiaryRelationships...");
        com.inov8.integration.middleware.prisim.InputHeader _getBeneficiaryRelationships_inputHeader = null;
        java.lang.String _getBeneficiaryRelationships_channelUserIdentifier = "";
        java.lang.String _getBeneficiaryRelationships_customerUserName = "";
        com.inov8.integration.middleware.prisim.BeneficiaryRelationshipOutputParams _getBeneficiaryRelationships__return = port.getBeneficiaryRelationships(_getBeneficiaryRelationships_inputHeader, _getBeneficiaryRelationships_channelUserIdentifier, _getBeneficiaryRelationships_customerUserName);
        System.out.println("getBeneficiaryRelationships.result=" + _getBeneficiaryRelationships__return);


        }
        {
        System.out.println("Invoking getTransactionHistory...");
        com.inov8.integration.middleware.prisim.InputHeader _getTransactionHistory_inputHeader = null;
        java.lang.String _getTransactionHistory_channelUserIdentifier = "";
        java.lang.String _getTransactionHistory_customerUserName = "";
        java.lang.String _getTransactionHistory_dateRange = "";
        java.lang.String _getTransactionHistory_transactionType = "";
        com.inov8.integration.middleware.prisim.TransactionHistoryOutputParams _getTransactionHistory__return = port.getTransactionHistory(_getTransactionHistory_inputHeader, _getTransactionHistory_channelUserIdentifier, _getTransactionHistory_customerUserName, _getTransactionHistory_dateRange, _getTransactionHistory_transactionType);
        System.out.println("getTransactionHistory.result=" + _getTransactionHistory__return);


        }
        {
        System.out.println("Invoking deleteScheduleTransaction...");
        com.inov8.integration.middleware.prisim.InputHeader _deleteScheduleTransaction_inputHeader = null;
        java.lang.String _deleteScheduleTransaction_channelUserIdentifier = "";
        java.lang.String _deleteScheduleTransaction_customerUserName = "";
        java.lang.String _deleteScheduleTransaction_transactionType = "";
        java.lang.String _deleteScheduleTransaction_batchId = "";
        com.inov8.integration.middleware.prisim.DeleteScheduleTransactionOutputParams _deleteScheduleTransaction__return = port.deleteScheduleTransaction(_deleteScheduleTransaction_inputHeader, _deleteScheduleTransaction_channelUserIdentifier, _deleteScheduleTransaction_customerUserName, _deleteScheduleTransaction_transactionType, _deleteScheduleTransaction_batchId);
        System.out.println("deleteScheduleTransaction.result=" + _deleteScheduleTransaction__return);


        }
        {
        System.out.println("Invoking getBankDetails...");
        com.inov8.integration.middleware.prisim.InputHeader _getBankDetails_inputHeader = null;
        java.lang.String _getBankDetails_channelUserIdentifier = "";
        java.lang.String _getBankDetails_customerUserName = "";
        com.inov8.integration.middleware.prisim.BankDetailsOutputParams _getBankDetails__return = port.getBankDetails(_getBankDetails_inputHeader, _getBankDetails_channelUserIdentifier, _getBankDetails_customerUserName);
        System.out.println("getBankDetails.result=" + _getBankDetails__return);


        }
        {
        System.out.println("Invoking changeSecretAnswer...");
        com.inov8.integration.middleware.prisim.InputHeader _changeSecretAnswer_inputHeader = null;
        java.lang.String _changeSecretAnswer_channelUserIdentifier = "";
        java.lang.String _changeSecretAnswer_customerUserName = "";
        com.inov8.integration.middleware.prisim.SecretQuestion _changeSecretAnswer_oldSecretQuestion = null;
        java.lang.String _changeSecretAnswer_oldSecretAnswer = "";
        com.inov8.integration.middleware.prisim.SecretQuestion _changeSecretAnswer_newSecretQuestion = null;
        java.lang.String _changeSecretAnswer_newSecretAnswer = "";
        com.inov8.integration.middleware.prisim.ChangeSecretAnswerOutputParams _changeSecretAnswer__return = port.changeSecretAnswer(_changeSecretAnswer_inputHeader, _changeSecretAnswer_channelUserIdentifier, _changeSecretAnswer_customerUserName, _changeSecretAnswer_oldSecretQuestion, _changeSecretAnswer_oldSecretAnswer, _changeSecretAnswer_newSecretQuestion, _changeSecretAnswer_newSecretAnswer);
        System.out.println("changeSecretAnswer.result=" + _changeSecretAnswer__return);


        }
        {
        System.out.println("Invoking setFirstTimeLogin...");
        com.inov8.integration.middleware.prisim.InputHeader _setFirstTimeLogin_inputHeader = null;
        java.lang.String _setFirstTimeLogin_channelUserIdentifier = "";
        java.lang.String _setFirstTimeLogin_customerUserName = "";
        com.inov8.integration.middleware.prisim.SetFirstTimeLoginOutputParams _setFirstTimeLogin__return = port.setFirstTimeLogin(_setFirstTimeLogin_inputHeader, _setFirstTimeLogin_channelUserIdentifier, _setFirstTimeLogin_customerUserName);
        System.out.println("setFirstTimeLogin.result=" + _setFirstTimeLogin__return);


        }
        {
        System.out.println("Invoking getPurposes...");
        com.inov8.integration.middleware.prisim.InputHeader _getPurposes_inputHeader = null;
        java.lang.String _getPurposes_channelUserIdentifier = "";
        java.lang.String _getPurposes_customerUserName = "";
        com.inov8.integration.middleware.prisim.PurposeOutputParams _getPurposes__return = port.getPurposes(_getPurposes_inputHeader, _getPurposes_channelUserIdentifier, _getPurposes_customerUserName);
        System.out.println("getPurposes.result=" + _getPurposes__return);


        }
        {
        System.out.println("Invoking viewScheduleFundsTransfer...");
        com.inov8.integration.middleware.prisim.InputHeader _viewScheduleFundsTransfer_inputHeader = null;
        java.lang.String _viewScheduleFundsTransfer_channelUserIdentifier = "";
        java.lang.String _viewScheduleFundsTransfer_customerUserName = "";
        java.lang.String _viewScheduleFundsTransfer_transactionType = "";
        com.inov8.integration.middleware.prisim.ViewScheduleFundsTransferOutputParams _viewScheduleFundsTransfer__return = port.viewScheduleFundsTransfer(_viewScheduleFundsTransfer_inputHeader, _viewScheduleFundsTransfer_channelUserIdentifier, _viewScheduleFundsTransfer_customerUserName, _viewScheduleFundsTransfer_transactionType);
        System.out.println("viewScheduleFundsTransfer.result=" + _viewScheduleFundsTransfer__return);


        }
        {
        System.out.println("Invoking addBeneficiaryAccount...");
        com.inov8.integration.middleware.prisim.InputHeader _addBeneficiaryAccount_inputHeader = null;
        com.inov8.integration.middleware.prisim.BeneficiaryAccount _addBeneficiaryAccount_beneficiaryAccount = null;
        com.inov8.integration.middleware.prisim.OTP _addBeneficiaryAccount_otp = null;
        java.lang.String _addBeneficiaryAccount_channelUserIdentifier = "";
        java.lang.String _addBeneficiaryAccount_customerUserName = "";
        com.inov8.integration.middleware.prisim.AddBeneficiaryOutputParams _addBeneficiaryAccount__return = port.addBeneficiaryAccount(_addBeneficiaryAccount_inputHeader, _addBeneficiaryAccount_beneficiaryAccount, _addBeneficiaryAccount_otp, _addBeneficiaryAccount_channelUserIdentifier, _addBeneficiaryAccount_customerUserName);
        System.out.println("addBeneficiaryAccount.result=" + _addBeneficiaryAccount__return);


        }
        {
        System.out.println("Invoking getBeneficiaryAccounts...");
        com.inov8.integration.middleware.prisim.InputHeader _getBeneficiaryAccounts_inputHeader = null;
        java.lang.String _getBeneficiaryAccounts_beneficiaryType = "";
        java.lang.String _getBeneficiaryAccounts_channelUserIdentifier = "";
        java.lang.String _getBeneficiaryAccounts_customerUserName = "";
        com.inov8.integration.middleware.prisim.BeneficiaryAccountOutputParams _getBeneficiaryAccounts__return = port.getBeneficiaryAccounts(_getBeneficiaryAccounts_inputHeader, _getBeneficiaryAccounts_beneficiaryType, _getBeneficiaryAccounts_channelUserIdentifier, _getBeneficiaryAccounts_customerUserName);
        System.out.println("getBeneficiaryAccounts.result=" + _getBeneficiaryAccounts__return);


        }
        {
        System.out.println("Invoking changeEmail...");
        com.inov8.integration.middleware.prisim.InputHeader _changeEmail_inputHeader = null;
        java.lang.String _changeEmail_channelUserIdentifier = "";
        java.lang.String _changeEmail_customerUserName = "";
        com.inov8.integration.middleware.prisim.SecretQuestion _changeEmail_secretQuestion = null;
        java.lang.String _changeEmail_secretAnswer = "";
        java.lang.String _changeEmail_oldEmail = "";
        java.lang.String _changeEmail_newEmail = "";
        com.inov8.integration.middleware.prisim.ChangeEmailOutputParams _changeEmail__return = port.changeEmail(_changeEmail_inputHeader, _changeEmail_channelUserIdentifier, _changeEmail_customerUserName, _changeEmail_secretQuestion, _changeEmail_secretAnswer, _changeEmail_oldEmail, _changeEmail_newEmail);
        System.out.println("changeEmail.result=" + _changeEmail__return);


        }
        {
        System.out.println("Invoking deleteBillPayee...");
        com.inov8.integration.middleware.prisim.InputHeader _deleteBillPayee_inputHeader = null;
        com.inov8.integration.middleware.prisim.BillPayee _deleteBillPayee_billPayee = null;
        java.lang.String _deleteBillPayee_channelUserIdentifier = "";
        java.lang.String _deleteBillPayee_customerUserName = "";
        com.inov8.integration.middleware.prisim.DeleteBillPayeeOutputParams _deleteBillPayee__return = port.deleteBillPayee(_deleteBillPayee_inputHeader, _deleteBillPayee_billPayee, _deleteBillPayee_channelUserIdentifier, _deleteBillPayee_customerUserName);
        System.out.println("deleteBillPayee.result=" + _deleteBillPayee__return);


        }
        {
        System.out.println("Invoking generateFinancialPIN...");
        com.inov8.integration.middleware.prisim.InputHeader _generateFinancialPIN_inputHeader = null;
        java.lang.String _generateFinancialPIN_financialPINNature = "";
        java.lang.String _generateFinancialPIN_channelUserIdentifier = "";
        java.lang.String _generateFinancialPIN_customerUserName = "";
        com.inov8.integration.middleware.prisim.GenerateFinancialPinOutputParams _generateFinancialPIN__return = port.generateFinancialPIN(_generateFinancialPIN_inputHeader, _generateFinancialPIN_financialPINNature, _generateFinancialPIN_channelUserIdentifier, _generateFinancialPIN_customerUserName);
        System.out.println("generateFinancialPIN.result=" + _generateFinancialPIN__return);


        }
        {
        System.out.println("Invoking modifyBeneficiaryAccount...");
        com.inov8.integration.middleware.prisim.InputHeader _modifyBeneficiaryAccount_inputHeader = null;
        com.inov8.integration.middleware.prisim.BeneficiaryAccount _modifyBeneficiaryAccount_beneficiaryAccount = null;
        com.inov8.integration.middleware.prisim.OTP _modifyBeneficiaryAccount_otp = null;
        java.lang.String _modifyBeneficiaryAccount_channelUserIdentifier = "";
        java.lang.String _modifyBeneficiaryAccount_customerUserName = "";
        com.inov8.integration.middleware.prisim.ModifyBeneficiaryAccountOutputParams _modifyBeneficiaryAccount__return = port.modifyBeneficiaryAccount(_modifyBeneficiaryAccount_inputHeader, _modifyBeneficiaryAccount_beneficiaryAccount, _modifyBeneficiaryAccount_otp, _modifyBeneficiaryAccount_channelUserIdentifier, _modifyBeneficiaryAccount_customerUserName);
        System.out.println("modifyBeneficiaryAccount.result=" + _modifyBeneficiaryAccount__return);


        }
        {
        System.out.println("Invoking getCardStatement...");
        com.inov8.integration.middleware.prisim.InputHeader _getCardStatement_inputHeader = null;
        com.inov8.integration.middleware.prisim.CardStatementFilter _getCardStatement_cardStatementFilter = null;
        java.lang.String _getCardStatement_channelUserIdentifier = "";
        java.lang.String _getCardStatement_customerUserName = "";
        java.lang.String _getCardStatement_cardNumber = "";
        com.inov8.integration.middleware.prisim.CardStatementOutputParams _getCardStatement__return = port.getCardStatement(_getCardStatement_inputHeader, _getCardStatement_cardStatementFilter, _getCardStatement_channelUserIdentifier, _getCardStatement_customerUserName, _getCardStatement_cardNumber);
        System.out.println("getCardStatement.result=" + _getCardStatement__return);


        }
        {
        System.out.println("Invoking getLoginHistory...");
        com.inov8.integration.middleware.prisim.InputHeader _getLoginHistory_inputHeader = null;
        java.lang.String _getLoginHistory_channelUserIdentifier = "";
        java.lang.String _getLoginHistory_customerUserName = "";
        com.inov8.integration.middleware.prisim.LoginHistoryOutputParams _getLoginHistory__return = port.getLoginHistory(_getLoginHistory_inputHeader, _getLoginHistory_channelUserIdentifier, _getLoginHistory_customerUserName);
        System.out.println("getLoginHistory.result=" + _getLoginHistory__return);


        }
        {
        System.out.println("Invoking billPaymentSchedule...");
        com.inov8.integration.middleware.prisim.InputHeader _billPaymentSchedule_inputHeader = null;
        java.lang.String _billPaymentSchedule_channelUserIdentifier = "";
        java.lang.String _billPaymentSchedule_customerUserName = "";
        com.inov8.integration.middleware.prisim.CustomerAccount _billPaymentSchedule_customerAccount = null;
        com.inov8.integration.middleware.prisim.BillPayee _billPaymentSchedule_payee = null;
        com.inov8.integration.middleware.prisim.PaymentDetailDTO _billPaymentSchedule_paymentDetailDTO = null;
        java.lang.String _billPaymentSchedule_financialPin = "";
        com.inov8.integration.middleware.prisim.BillPaymentScheduleOutputParams _billPaymentSchedule__return = port.billPaymentSchedule(_billPaymentSchedule_inputHeader, _billPaymentSchedule_channelUserIdentifier, _billPaymentSchedule_customerUserName, _billPaymentSchedule_customerAccount, _billPaymentSchedule_payee, _billPaymentSchedule_paymentDetailDTO, _billPaymentSchedule_financialPin);
        System.out.println("billPaymentSchedule.result=" + _billPaymentSchedule__return);


        }
        {
        System.out.println("Invoking expireFinancialPIN...");
        com.inov8.integration.middleware.prisim.InputHeader _expireFinancialPIN_inputHeader = null;
        java.lang.String _expireFinancialPIN_channelUserIdentifier = "";
        java.lang.String _expireFinancialPIN_customerUserName = "";
        com.inov8.integration.middleware.prisim.ExpireFinancialPinOutputParams _expireFinancialPIN__return = port.expireFinancialPIN(_expireFinancialPIN_inputHeader, _expireFinancialPIN_channelUserIdentifier, _expireFinancialPIN_customerUserName);
        System.out.println("expireFinancialPIN.result=" + _expireFinancialPIN__return);


        }
        {
        System.out.println("Invoking getAccountStatement...");
        com.inov8.integration.middleware.prisim.InputHeader _getAccountStatement_inputHeader = null;
        com.inov8.integration.middleware.prisim.AccountStatementFilter _getAccountStatement_accountStatementFilter = null;
        java.lang.String _getAccountStatement_channelUserIdentifier = "";
        java.lang.String _getAccountStatement_customerUserName = "";
        java.lang.String _getAccountStatement_accountNumber = "";
        com.inov8.integration.middleware.prisim.AccountStatementOutputParams _getAccountStatement__return = port.getAccountStatement(_getAccountStatement_inputHeader, _getAccountStatement_accountStatementFilter, _getAccountStatement_channelUserIdentifier, _getAccountStatement_customerUserName, _getAccountStatement_accountNumber);
        System.out.println("getAccountStatement.result=" + _getAccountStatement__return);


        }
        {
        System.out.println("Invoking deleteBeneficiaryAccount...");
        com.inov8.integration.middleware.prisim.InputHeader _deleteBeneficiaryAccount_inputHeader = null;
        com.inov8.integration.middleware.prisim.BeneficiaryAccount _deleteBeneficiaryAccount_beneficiaryAccount = null;
        java.lang.String _deleteBeneficiaryAccount_channelUserIdentifier = "";
        java.lang.String _deleteBeneficiaryAccount_customerUserName = "";
        com.inov8.integration.middleware.prisim.DeleteBeneficiaryAccountOutputParams _deleteBeneficiaryAccount__return = port.deleteBeneficiaryAccount(_deleteBeneficiaryAccount_inputHeader, _deleteBeneficiaryAccount_beneficiaryAccount, _deleteBeneficiaryAccount_channelUserIdentifier, _deleteBeneficiaryAccount_customerUserName);
        System.out.println("deleteBeneficiaryAccount.result=" + _deleteBeneficiaryAccount__return);


        }
        {
        System.out.println("Invoking getBillPayee...");
        com.inov8.integration.middleware.prisim.InputHeader _getBillPayee_inputHeader = null;
        java.lang.String _getBillPayee_channelUserIdentifier = "";
        java.lang.String _getBillPayee_customerUserName = "";
        com.inov8.integration.middleware.prisim.BillPayeeOutputParams _getBillPayee__return = port.getBillPayee(_getBillPayee_inputHeader, _getBillPayee_channelUserIdentifier, _getBillPayee_customerUserName);
        System.out.println("getBillPayee.result=" + _getBillPayee__return);


        }
        {
        System.out.println("Invoking editScheduleTransaction...");
        com.inov8.integration.middleware.prisim.InputHeader _editScheduleTransaction_inputHeader = null;
        java.lang.String _editScheduleTransaction_channelUserIdentifier = "";
        java.lang.String _editScheduleTransaction_customerUserName = "";
        java.lang.String _editScheduleTransaction_transactionType = "";
        java.lang.String _editScheduleTransaction_recurPattern = "";
        java.lang.String _editScheduleTransaction_recurEndType = "";
        java.lang.String _editScheduleTransaction_startDate = "";
        java.lang.String _editScheduleTransaction_endDate = "";
        java.lang.String _editScheduleTransaction_noOfOccurrence = "";
        java.lang.String _editScheduleTransaction_batchId = "";
        com.inov8.integration.middleware.prisim.EditScheduleTransactionOutputParams _editScheduleTransaction__return = port.editScheduleTransaction(_editScheduleTransaction_inputHeader, _editScheduleTransaction_channelUserIdentifier, _editScheduleTransaction_customerUserName, _editScheduleTransaction_transactionType, _editScheduleTransaction_recurPattern, _editScheduleTransaction_recurEndType, _editScheduleTransaction_startDate, _editScheduleTransaction_endDate, _editScheduleTransaction_noOfOccurrence, _editScheduleTransaction_batchId);
        System.out.println("editScheduleTransaction.result=" + _editScheduleTransaction__return);


        }
        {
        System.out.println("Invoking addBillPayee...");
        com.inov8.integration.middleware.prisim.InputHeader _addBillPayee_inputHeader = null;
        com.inov8.integration.middleware.prisim.BillPayee _addBillPayee_billPayee = null;
        com.inov8.integration.middleware.prisim.OTP _addBillPayee_otp = null;
        java.lang.String _addBillPayee_channelUserIdentifier = "";
        java.lang.String _addBillPayee_customerUserName = "";
        com.inov8.integration.middleware.prisim.AddBillPayeeOutputParams _addBillPayee__return = port.addBillPayee(_addBillPayee_inputHeader, _addBillPayee_billPayee, _addBillPayee_otp, _addBillPayee_channelUserIdentifier, _addBillPayee_customerUserName);
        System.out.println("addBillPayee.result=" + _addBillPayee__return);


        }
        {
        System.out.println("Invoking generateMobilePin...");
        com.inov8.integration.middleware.prisim.InputHeader _generateMobilePin_inputHeader = null;
        java.lang.String _generateMobilePin_channelUserIdentifier = "";
        java.lang.String _generateMobilePin_customerUserName = "";
        com.inov8.integration.middleware.prisim.GenerateMobilePinOutputParams _generateMobilePin__return = port.generateMobilePin(_generateMobilePin_inputHeader, _generateMobilePin_channelUserIdentifier, _generateMobilePin_customerUserName);
        System.out.println("generateMobilePin.result=" + _generateMobilePin__return);


        }
        {
        System.out.println("Invoking auditLoggging...");
        com.inov8.integration.middleware.prisim.InputHeader _auditLoggging_inputHeader = null;
        java.lang.String _auditLoggging_channelUserIdentifier = "";
        java.lang.String _auditLoggging_customerUserName = "";
        java.lang.String _auditLoggging_transactionType = "";
        com.inov8.integration.middleware.prisim.AuditLoggingRequest _auditLoggging_auditLogging = null;
        com.inov8.integration.middleware.prisim.AuditLoggingOutputParams _auditLoggging__return = port.auditLoggging(_auditLoggging_inputHeader, _auditLoggging_channelUserIdentifier, _auditLoggging_customerUserName, _auditLoggging_transactionType, _auditLoggging_auditLogging);
        System.out.println("auditLoggging.result=" + _auditLoggging__return);


        }
        {
        System.out.println("Invoking viewScheduledBillPayment...");
        com.inov8.integration.middleware.prisim.InputHeader _viewScheduledBillPayment_inputHeader = null;
        java.lang.String _viewScheduledBillPayment_channelUserIdentifier = "";
        java.lang.String _viewScheduledBillPayment_customerUserName = "";
        com.inov8.integration.middleware.prisim.ViewScheduledBillPaymentOutputParams _viewScheduledBillPayment__return = port.viewScheduledBillPayment(_viewScheduledBillPayment_inputHeader, _viewScheduledBillPayment_channelUserIdentifier, _viewScheduledBillPayment_customerUserName);
        System.out.println("viewScheduledBillPayment.result=" + _viewScheduledBillPayment__return);


        }
        {
        System.out.println("Invoking verifyFinancialPIN...");
        com.inov8.integration.middleware.prisim.InputHeader _verifyFinancialPIN_inputHeader = null;
        java.lang.String _verifyFinancialPIN_financialPIN = "";
        java.lang.String _verifyFinancialPIN_channelUserIdentifier = "";
        java.lang.String _verifyFinancialPIN_customerUserName = "";
        com.inov8.integration.middleware.prisim.VerifyFinancialPinOutputParams _verifyFinancialPIN__return = port.verifyFinancialPIN(_verifyFinancialPIN_inputHeader, _verifyFinancialPIN_financialPIN, _verifyFinancialPIN_channelUserIdentifier, _verifyFinancialPIN_customerUserName);
        System.out.println("verifyFinancialPIN.result=" + _verifyFinancialPIN__return);


        }
        {
        System.out.println("Invoking getBillingCompanyTypes...");
        com.inov8.integration.middleware.prisim.InputHeader _getBillingCompanyTypes_inputHeader = null;
        java.lang.String _getBillingCompanyTypes_channelUserIdentifier = "";
        java.lang.String _getBillingCompanyTypes_customerUserName = "";
        com.inov8.integration.middleware.prisim.BillingCompanyTypeOutputParams _getBillingCompanyTypes__return = port.getBillingCompanyTypes(_getBillingCompanyTypes_inputHeader, _getBillingCompanyTypes_channelUserIdentifier, _getBillingCompanyTypes_customerUserName);
        System.out.println("getBillingCompanyTypes.result=" + _getBillingCompanyTypes__return);


        }
        {
        System.out.println("Invoking forgotSecretAnswer...");
        com.inov8.integration.middleware.prisim.InputHeader _forgotSecretAnswer_inputHeader = null;
        java.lang.String _forgotSecretAnswer_channelUserIdentifier = "";
        java.lang.String _forgotSecretAnswer_customerUserName = "";
        com.inov8.integration.middleware.prisim.SecretQuestion _forgotSecretAnswer_newSecretQuestion = null;
        java.lang.String _forgotSecretAnswer_newSecretAnswer = "";
        java.lang.String _forgotSecretAnswer_mobilePin = "";
        com.inov8.integration.middleware.prisim.ForgotSecretAnswerOutputParams _forgotSecretAnswer__return = port.forgotSecretAnswer(_forgotSecretAnswer_inputHeader, _forgotSecretAnswer_channelUserIdentifier, _forgotSecretAnswer_customerUserName, _forgotSecretAnswer_newSecretQuestion, _forgotSecretAnswer_newSecretAnswer, _forgotSecretAnswer_mobilePin);
        System.out.println("forgotSecretAnswer.result=" + _forgotSecretAnswer__return);


        }

        System.exit(0);
    }

}
