
package com.inov8.microbank.ws.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IVRRequestHandlerService", targetNamespace = "http://service.microbank.inov8.com/", wsdlLocation = "http://microbankservice:8080/i8Microbank/IVRRequestHandlerPort?wsdl")
@Deprecated
public class IVRRequestHandlerService
    extends Service
{

    private final static URL IVRREQUESTHANDLERSERVICE_WSDL_LOCATION;
    private final static Logger logger = LoggerFactory.getLogger(IVRRequestHandlerService.class);

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.inov8.microbank.ws.service.IVRRequestHandlerService.class.getResource(".");
            url = new URL(baseUrl, "http://microbankservice:8080/i8Microbank/IVRRequestHandlerPort?wsdl");
        } catch (MalformedURLException e) {
            logger.error("Failed to create URL for the wsdl Location: 'http://microbankservice:8080/i8Microbank/IVRRequestHandlerPort?wsdl', retrying as a local file");
            logger.error(e.getMessage());
        }
        IVRREQUESTHANDLERSERVICE_WSDL_LOCATION = url;
    }

    public IVRRequestHandlerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IVRRequestHandlerService() {
        super(IVRREQUESTHANDLERSERVICE_WSDL_LOCATION, new QName("http://service.microbank.inov8.com/", "IVRRequestHandlerService"));
    }

    /**
     * 
     * @return
     *     returns IVRRequestHandlerDelegate
     */
    @WebEndpoint(name = "IVRRequestHandlerPort")
    public IVRRequestHandlerDelegate getIVRRequestHandlerPort() {
        return super.getPort(new QName("http://service.microbank.inov8.com/", "IVRRequestHandlerPort"), IVRRequestHandlerDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IVRRequestHandlerDelegate
     */
    @WebEndpoint(name = "IVRRequestHandlerPort")
    public IVRRequestHandlerDelegate getIVRRequestHandlerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.microbank.inov8.com/", "IVRRequestHandlerPort"), IVRRequestHandlerDelegate.class, features);
    }

}
