package com.inov8.integration.middleware.abl.mobapp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-10-11T05:10:37.729-07:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "ABLMobileAppService", 
                  wsdlLocation = "file:IABLMobileAppService.wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class ABLMobileAppService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ABLMobileAppService");
    public final static QName BasicHttpBindingIABLMobileAppService = new QName("http://tempuri.org/", "BasicHttpBinding_IABLMobileAppService");
    static {
        URL url = null;
        try {
            url = new URL("file:IABLMobileAppService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ABLMobileAppService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:IABLMobileAppService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ABLMobileAppService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ABLMobileAppService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ABLMobileAppService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ABLMobileAppService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ABLMobileAppService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ABLMobileAppService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IABLMobileAppService
     */
    @WebEndpoint(name = "BasicHttpBinding_IABLMobileAppService")
    public IABLMobileAppService getBasicHttpBindingIABLMobileAppService() {
        return super.getPort(BasicHttpBindingIABLMobileAppService, IABLMobileAppService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IABLMobileAppService
     */
    @WebEndpoint(name = "BasicHttpBinding_IABLMobileAppService")
    public IABLMobileAppService getBasicHttpBindingIABLMobileAppService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIABLMobileAppService, IABLMobileAppService.class, features);
    }

}
