package com.inov8.integration.middleware.abl.mobapp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-10-11T05:10:37.715-07:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IABLMobileAppService")
@XmlSeeAlso({ObjectFactory.class})
public interface IABLMobileAppService {

    @WebMethod(operationName = "Login", action = "http://tempuri.org/IABLMobileAppService/Login")
    @Action(input = "http://tempuri.org/IABLMobileAppService/Login", output = "http://tempuri.org/IABLMobileAppService/LoginResponse")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.mobapp.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.mobapp.LoginResponse")
    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.abl.mobapp.LoginOutputParams login(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.abl.mobapp.InputHeader inputHeader,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "SubscriptionCheck", targetNamespace = "http://tempuri.org/")
        java.lang.String subscriptionCheck
    );

    @WebMethod(operationName = "VerifyPassword", action = "http://tempuri.org/IABLMobileAppService/VerifyPassword")
    @Action(input = "http://tempuri.org/IABLMobileAppService/VerifyPassword", output = "http://tempuri.org/IABLMobileAppService/VerifyPasswordResponse")
    @RequestWrapper(localName = "VerifyPassword", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.mobapp.VerifyPassword")
    @ResponseWrapper(localName = "VerifyPasswordResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.mobapp.VerifyPasswordResponse")
    @WebResult(name = "VerifyPasswordResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.abl.mobapp.PasswordOutputParams verifyPassword(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.abl.mobapp.InputHeader inputHeader,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "PasswordPattern", targetNamespace = "http://tempuri.org/")
        java.lang.String passwordPattern,
        @WebParam(name = "CustomerPassword", targetNamespace = "http://tempuri.org/")
        java.lang.String customerPassword
    );

    @WebMethod(operationName = "GetAccounts", action = "http://tempuri.org/IABLMobileAppService/GetAccounts")
    @Action(input = "http://tempuri.org/IABLMobileAppService/GetAccounts", output = "http://tempuri.org/IABLMobileAppService/GetAccountsResponse")
    @RequestWrapper(localName = "GetAccounts", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.mobapp.GetAccounts")
    @ResponseWrapper(localName = "GetAccountsResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.mobapp.GetAccountsResponse")
    @WebResult(name = "GetAccountsResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.abl.mobapp.GetAccountsOutputParams getAccounts(
        @WebParam(name = "InputHeader", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.abl.mobapp.InputHeader inputHeader,
        @WebParam(name = "CustomerUserName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerUserName,
        @WebParam(name = "CNIC", targetNamespace = "http://tempuri.org/")
        java.lang.String cnic
    );
}
