package com.inov8.integration.middleware.bop.iflexService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-12-07T10:12:52.023+05:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IFlexService")
@XmlSeeAlso({ObjectFactory.class})
public interface IFlexService {

    @WebMethod(operationName = "IsFiler", action = "http://tempuri.org/IFlexService/IsFiler")
    @Action(input = "http://tempuri.org/IFlexService/IsFiler", output = "http://tempuri.org/IFlexService/IsFilerResponse")
    @RequestWrapper(localName = "IsFiler", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.iflexService.IsFiler")
    @ResponseWrapper(localName = "IsFilerResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.iflexService.IsFilerResponse")
    @WebResult(name = "IsFilerResult", targetNamespace = "http://tempuri.org/")
    public Boolean isFiler(
            @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
                    com.inov8.integration.middleware.bop.iflexService.IChannelRequest request,
            @WebParam(name = "AccountNumber", targetNamespace = "http://tempuri.org/")
                    String accountNumber
    );

    @WebMethod(operationName = "GetData", action = "http://tempuri.org/IFlexService/GetData")
    @Action(input = "http://tempuri.org/IFlexService/GetData", output = "http://tempuri.org/IFlexService/GetDataResponse")
    @RequestWrapper(localName = "GetData", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.iflexService.GetData")
    @ResponseWrapper(localName = "GetDataResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.iflexService.GetDataResponse")
    @WebResult(name = "GetDataResult", targetNamespace = "http://tempuri.org/")
    public String getData(
            @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
                    com.inov8.integration.middleware.bop.iflexService.IChannelRequest request,
            @WebParam(name = "AccountNumber", targetNamespace = "http://tempuri.org/")
                    String accountNumber
    );

    @WebMethod(operationName = "GetGLDescription", action = "http://tempuri.org/IFlexService/GetGLDescription")
    @Action(input = "http://tempuri.org/IFlexService/GetGLDescription", output = "http://tempuri.org/IFlexService/GetGLDescriptionResponse")
    @RequestWrapper(localName = "GetGLDescription", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.iflexService.GetGLDescription")
    @ResponseWrapper(localName = "GetGLDescriptionResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.iflexService.GetGLDescriptionResponse")
    @WebResult(name = "GetGLDescriptionResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.bop.iflexService.GetGLDescriptionResponse.GetGLDescriptionResult getGLDescription(
            @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
                    com.inov8.integration.middleware.bop.iflexService.IChannelRequest request,
            @WebParam(name = "GLAccountNumber", targetNamespace = "http://tempuri.org/")
                    String glAccountNumber
    );

    @WebMethod(operationName = "GetAccountMapping", action = "http://tempuri.org/IFlexService/GetAccountMapping")
    @Action(input = "http://tempuri.org/IFlexService/GetAccountMapping", output = "http://tempuri.org/IFlexService/GetAccountMappingResponse")
    @RequestWrapper(localName = "GetAccountMapping", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.iflexService.GetAccountMapping")
    @ResponseWrapper(localName = "GetAccountMappingResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.iflexService.GetAccountMappingResponse")
    @WebResult(name = "GetAccountMappingResult", targetNamespace = "http://tempuri.org/")
    public String getAccountMapping(
            @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
                    com.inov8.integration.middleware.bop.iflexService.IChannelRequest request,
            @WebParam(name = "AccountNumber", targetNamespace = "http://tempuri.org/")
                    String accountNumber
    );

    @WebMethod(operationName = "ChannelActivation", action = "http://tempuri.org/IFlexService/ChannelActivation")
    @Action(input = "http://tempuri.org/IFlexService/ChannelActivation", output = "http://tempuri.org/IFlexService/ChannelActivationResponse")
    @RequestWrapper(localName = "ChannelActivation", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.iflexService.ChannelActivation")
    @ResponseWrapper(localName = "ChannelActivationResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.iflexService.ChannelActivationResponse")
    @WebResult(name = "ChannelActivationResult", targetNamespace = "http://tempuri.org/")
    public String channelActivation(
            @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
                    com.inov8.integration.middleware.bop.iflexService.IChannelRequest request
    );

    @WebMethod(operationName = "GetAccountStatement", action = "http://tempuri.org/IFlexService/GetAccountStatement")
    @Action(input = "http://tempuri.org/IFlexService/GetAccountStatement", output = "http://tempuri.org/IFlexService/GetAccountStatementResponse")
    @RequestWrapper(localName = "GetAccountStatement", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.iflexService.GetAccountStatement")
    @ResponseWrapper(localName = "GetAccountStatementResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.iflexService.GetAccountStatementResponse")
    public void getAccountStatement(
            @WebParam(name = "Request", targetNamespace = "http://tempuri.org/")
                    com.inov8.integration.middleware.bop.iflexService.IChannelRequest request,
            @WebParam(name = "FromDate", targetNamespace = "http://tempuri.org/")
                    javax.xml.datatype.XMLGregorianCalendar fromDate,
            @WebParam(name = "ToDate", targetNamespace = "http://tempuri.org/")
                    javax.xml.datatype.XMLGregorianCalendar toDate,
            @WebParam(name = "AccountNumber", targetNamespace = "http://tempuri.org/")
                    String accountNumber,
            @WebParam(name = "IsMiniStatemnet", targetNamespace = "http://tempuri.org/")
                    Boolean isMiniStatemnet,
            @WebParam(mode = WebParam.Mode.OUT, name = "GetAccountStatementResult", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<com.inov8.integration.middleware.bop.iflexService.GetAccountStatementResponse.GetAccountStatementResult> getAccountStatementResult,
            @WebParam(mode = WebParam.Mode.OUT, name = "ErrorCode", targetNamespace = "http://tempuri.org/")
                    javax.xml.ws.Holder<String> errorCode
    );
}
