package com.inov8.integration.middleware.meezan;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-17T18:10:39.407+05:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "MBL_T24_Reversal_APIHttpService", 
                  wsdlLocation = "file:MBL_T24_Reversal_API.wsdl",
                  targetNamespace = "http://MBL_T24_Reversal_API") 
public class MBLT24ReversalAPIHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://MBL_T24_Reversal_API", "MBL_T24_Reversal_APIHttpService");
    public final static QName MBLT24ReversalAPIHttpPort = new QName("http://MBL_T24_Reversal_API", "MBL_T24_Reversal_APIHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:MBL_T24_Reversal_API.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MBLT24ReversalAPIHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:MBL_T24_Reversal_API.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MBLT24ReversalAPIHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MBLT24ReversalAPIHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MBLT24ReversalAPIHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MBLT24ReversalAPIHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MBLT24ReversalAPIHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MBLT24ReversalAPIHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MBLT24ReversalAPI
     */
    @WebEndpoint(name = "MBL_T24_Reversal_APIHttpPort")
    public MBLT24ReversalAPI getMBLT24ReversalAPIHttpPort() {
        return super.getPort(MBLT24ReversalAPIHttpPort, MBLT24ReversalAPI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MBLT24ReversalAPI
     */
    @WebEndpoint(name = "MBL_T24_Reversal_APIHttpPort")
    public MBLT24ReversalAPI getMBLT24ReversalAPIHttpPort(WebServiceFeature... features) {
        return super.getPort(MBLT24ReversalAPIHttpPort, MBLT24ReversalAPI.class, features);
    }

}
