
package com.inov8.integration.middleware.meezan;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-17T18:10:39.358+05:00
 * Generated source version: 3.1.6
 * 
 */
public final class MBLT24ReversalAPI_MBLT24ReversalAPIHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://MBL_T24_Reversal_API", "MBL_T24_Reversal_APIHttpService");

    private MBLT24ReversalAPI_MBLT24ReversalAPIHttpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MBLT24ReversalAPIHttpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MBLT24ReversalAPIHttpService ss = new MBLT24ReversalAPIHttpService(wsdlURL, SERVICE_NAME);
        MBLT24ReversalAPI port = ss.getMBLT24ReversalAPIHttpPort();  
        
        {
        System.out.println("Invoking ifxReversal...");
        com.inov8.integration.middleware.meezan.IFXReversalRequest _ifxReversal_ifxReversalParameters = null;
        com.inov8.integration.middleware.meezan.IFXReversalResponse _ifxReversal__return = port.ifxReversal(_ifxReversal_ifxReversalParameters);
        System.out.println("ifxReversal.result=" + _ifxReversal__return);


        }

        System.exit(0);
    }

}
