package com.inov8.integration.middleware.meezan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-03-17T18:10:39.400+05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://MBL_T24_Reversal_API", name = "MBL_T24_Reversal_API")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MBLT24ReversalAPI {

    @WebResult(name = "IFXReversalResponse", targetNamespace = "http://MBL_T24_Reversal_API", partName = "IFXReversalResult")
    @WebMethod(operationName = "IFXReversal", action = "http://MBL_T24_Reversal_API/IFXReversal")
    public IFXReversalResponse ifxReversal(
        @WebParam(partName = "IFXReversalParameters", name = "IFXReversalRequest", targetNamespace = "http://MBL_T24_Reversal_API")
        IFXReversalRequest ifxReversalParameters
    );
}
