# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'JSBL-BB' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JSBL-BB

    pod 'AEXML'
    pod 'CryptoSwift', '= 0.7.2'
    pod 'IQKeyboardManagerSwift'
    pod 'GoogleMaps', '= 2.2.0'
    pod 'ActionSheetPicker-3.0', '~> 2.2.0'
    pod 'EYImageSlider'
    pod 'Kingfisher', '~> 4.0'
    pod 'SwiftyJSON’
    pod 'Firebase/Analytics'
    pod 'JavaScriptKit', '~> 2.0'
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
