package com.inov8.integration.middleware.bop.nadra;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2020-02-21T18:56:01.668+05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IRelayService")
@XmlSeeAlso({ObjectFactory.class})
public interface IRelayService {

    @WebMethod(operationName = "GetExistingVerisys", action = "http://tempuri.org/IRelayService/GetExistingVerisys")
    @Action(input = "http://tempuri.org/IRelayService/GetExistingVerisys", output = "http://tempuri.org/IRelayService/GetExistingVerisysResponse")
    @RequestWrapper(localName = "GetExistingVerisys", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.nadra.GetExistingVerisys")
    @ResponseWrapper(localName = "GetExistingVerisysResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.nadra.GetExistingVerisysResponse")
    @WebResult(name = "GetExistingVerisysResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.bop.nadra.CitizenVerificationDTO getExistingVerisys(
        @WebParam(name = "Credentials", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.bop.nadra.UserCredentials credentials,
        @WebParam(name = "CitizenNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String citizenNumber,
        @WebParam(name = "Type", targetNamespace = "http://tempuri.org/")
        java.lang.Integer type
    );

    @WebMethod(operationName = "VerifyUser", action = "http://tempuri.org/IRelayService/VerifyUser")
    @Action(input = "http://tempuri.org/IRelayService/VerifyUser", output = "http://tempuri.org/IRelayService/VerifyUserResponse")
    @RequestWrapper(localName = "VerifyUser", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.nadra.VerifyUser")
    @ResponseWrapper(localName = "VerifyUserResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.nadra.VerifyUserResponse")
    @WebResult(name = "VerifyUserResult", targetNamespace = "http://tempuri.org/")
    public java.lang.Boolean verifyUser(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    @WebMethod(operationName = "VerifyCitizen", action = "http://tempuri.org/IRelayService/VerifyCitizen")
    @Action(input = "http://tempuri.org/IRelayService/VerifyCitizen", output = "http://tempuri.org/IRelayService/VerifyCitizenResponse")
    @RequestWrapper(localName = "VerifyCitizen", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.nadra.VerifyCitizen")
    @ResponseWrapper(localName = "VerifyCitizenResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.nadra.VerifyCitizenResponse")
    @WebResult(name = "VerifyCitizenResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.bop.nadra.CitizenVerificationDTO verifyCitizen(
        @WebParam(name = "Credentials", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.bop.nadra.UserCredentials credentials,
        @WebParam(name = "NadraDTO", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.bop.nadra.NADRADTO nadraDTO
    );

    @WebMethod(operationName = "VerifyCitizenWithSegment", action = "http://tempuri.org/IRelayService/VerifyCitizenWithSegment")
    @Action(input = "http://tempuri.org/IRelayService/VerifyCitizenWithSegment", output = "http://tempuri.org/IRelayService/VerifyCitizenWithSegmentResponse")
    @RequestWrapper(localName = "VerifyCitizenWithSegment", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.nadra.VerifyCitizenWithSegment")
    @ResponseWrapper(localName = "VerifyCitizenWithSegmentResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.nadra.VerifyCitizenWithSegmentResponse")
    @WebResult(name = "VerifyCitizenWithSegmentResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.bop.nadra.CitizenVerificationDTO verifyCitizenWithSegment(
        @WebParam(name = "Credentials", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.bop.nadra.UserCredentials credentials,
        @WebParam(name = "NadraDTO", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.bop.nadra.NADRADTO nadraDTO
    );

    @WebMethod(operationName = "VerifyCitizenLocally", action = "http://tempuri.org/IRelayService/VerifyCitizenLocally")
    @Action(input = "http://tempuri.org/IRelayService/VerifyCitizenLocally", output = "http://tempuri.org/IRelayService/VerifyCitizenLocallyResponse")
    @RequestWrapper(localName = "VerifyCitizenLocally", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.nadra.VerifyCitizenLocally")
    @ResponseWrapper(localName = "VerifyCitizenLocallyResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.nadra.VerifyCitizenLocallyResponse")
    @WebResult(name = "VerifyCitizenLocallyResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.bop.nadra.CitizenVerificationLocalDTO verifyCitizenLocally(
        @WebParam(name = "Credentials", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.bop.nadra.UserCredentials credentials,
        @WebParam(name = "CitizenNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String citizenNumber
    );

    @WebMethod(operationName = "CheckVerisysBYSegement", action = "http://tempuri.org/IRelayService/CheckVerisysBYSegement")
    @Action(input = "http://tempuri.org/IRelayService/CheckVerisysBYSegement", output = "http://tempuri.org/IRelayService/CheckVerisysBYSegementResponse")
    @RequestWrapper(localName = "CheckVerisysBYSegement", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.nadra.CheckVerisysBYSegement")
    @ResponseWrapper(localName = "CheckVerisysBYSegementResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.nadra.CheckVerisysBYSegementResponse")
    @WebResult(name = "CheckVerisysBYSegementResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.bop.nadra.OTCVerificationDTO checkVerisysBYSegement(
        @WebParam(name = "Credentials", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.bop.nadra.UserCredentials credentials,
        @WebParam(name = "CNIC", targetNamespace = "http://tempuri.org/")
        java.lang.String cnic,
        @WebParam(name = "Type", targetNamespace = "http://tempuri.org/")
        java.lang.Integer type
    );

    @WebMethod(operationName = "VerifyOTCTransaction", action = "http://tempuri.org/IRelayService/VerifyOTCTransaction")
    @Action(input = "http://tempuri.org/IRelayService/VerifyOTCTransaction", output = "http://tempuri.org/IRelayService/VerifyOTCTransactionResponse")
    @RequestWrapper(localName = "VerifyOTCTransaction", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.nadra.VerifyOTCTransaction")
    @ResponseWrapper(localName = "VerifyOTCTransactionResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.nadra.VerifyOTCTransactionResponse")
    @WebResult(name = "VerifyOTCTransactionResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.bop.nadra.OTCVerificationDTO verifyOTCTransaction(
        @WebParam(name = "Credentials", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.bop.nadra.UserCredentials credentials,
        @WebParam(name = "NadraDTO", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.bop.nadra.OTCNADRADTO nadraDTO
    );
}
