package com.inov8.integration.middleware.daewoo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-11-20T23:12:48.063-08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://daewoowsdl.com/", name = "tmsWSSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TmsWSSoap {

    @WebMethod(action = "http://daewoowsdl.com/getRoutes")
    @RequestWrapper(localName = "getRoutes", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetRoutes")
    @ResponseWrapper(localName = "getRoutesResponse", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetRoutesResponse")
    @WebResult(name = "getRoutesResult", targetNamespace = "http://daewoowsdl.com/")
    public java.lang.String getRoutes(
        @WebParam(name = "CLIENT_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientID,
        @WebParam(name = "CLIENT_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientPASSWORD,
        @WebParam(name = "DEPARTURE_DATE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String departureDATE,
        @WebParam(name = "DEPARTURE_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String departureID,
        @WebParam(name = "ARRIVAL_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String arrivalID
    );

    @WebMethod(action = "http://daewoowsdl.com/getBookingDetails")
    @RequestWrapper(localName = "getBookingDetails", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetBookingDetails")
    @ResponseWrapper(localName = "getBookingDetailsResponse", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetBookingDetailsResponse")
    @WebResult(name = "getBookingDetailsResult", targetNamespace = "http://daewoowsdl.com/")
    public java.lang.String getBookingDetails(
        @WebParam(name = "CLIENT_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientID,
        @WebParam(name = "CLIENT_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientPASSWORD,
        @WebParam(name = "BOOK_NUMBER", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String bookNUMBER,
        @WebParam(name = "PHONE_NUMBER", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String phoneNUMBER
    );

    @WebMethod(operationName = "CTR", action = "http://daewoowsdl.com/CTR")
    @RequestWrapper(localName = "CTR", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.CTR")
    @ResponseWrapper(localName = "CTRResponse", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.CTRResponse")
    @WebResult(name = "CTRResult", targetNamespace = "http://daewoowsdl.com/")
    public java.lang.String ctr(
        @WebParam(name = "CLIENT_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientID,
        @WebParam(name = "CLIENT_SECRET", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientSECRET,
        @WebParam(name = "CLIENT_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientPASSWORD
    );

    @WebMethod(action = "http://daewoowsdl.com/getSeatQuota")
    @RequestWrapper(localName = "getSeatQuota", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetSeatQuota")
    @ResponseWrapper(localName = "getSeatQuotaResponse", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetSeatQuotaResponse")
    @WebResult(name = "getSeatQuotaResult", targetNamespace = "http://daewoowsdl.com/")
    public java.lang.String getSeatQuota(
        @WebParam(name = "CLIENT_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientID,
        @WebParam(name = "CLIENT_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientPASSWORD,
        @WebParam(name = "SCHEDULE_CODE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String scheduleCODE,
        @WebParam(name = "QUOTA_DATE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String quotaDATE,
        @WebParam(name = "QUOTA_DEPARTURE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String quotaDEPARTURE,
        @WebParam(name = "QUOTA_ARRIVAL", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String quotaARRIVAL
    );

    @WebMethod(action = "http://daewoowsdl.com/getDepartures")
    @RequestWrapper(localName = "getDepartures", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetDepartures")
    @ResponseWrapper(localName = "getDeparturesResponse", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetDeparturesResponse")
    @WebResult(name = "getDeparturesResult", targetNamespace = "http://daewoowsdl.com/")
    public java.lang.String getDepartures(
        @WebParam(name = "CLIENT_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientID,
        @WebParam(name = "CLIENT_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientPASSWORD
    );

    @WebMethod(action = "http://daewoowsdl.com/getBooking")
    @RequestWrapper(localName = "getBooking", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetBooking")
    @ResponseWrapper(localName = "getBookingResponse", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetBookingResponse")
    @WebResult(name = "getBookingResult", targetNamespace = "http://daewoowsdl.com/")
    public java.lang.String getBooking(
        @WebParam(name = "CLIENT_TOKEN", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientTOKEN,
        @WebParam(name = "USER_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String userID,
        @WebParam(name = "USER_PASS", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String userPASS,
        @WebParam(name = "P_DATE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pDATE,
        @WebParam(name = "P_TIME", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pTIME,
        @WebParam(name = "P_SCHEDULE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pSCHEDULE,
        @WebParam(name = "P_TIMECODE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pTIMECODE,
        @WebParam(name = "P_ROUTE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pROUTE,
        @WebParam(name = "P_DEPARTURE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pDEPARTURE,
        @WebParam(name = "P_ARRIVAL", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pARRIVAL,
        @WebParam(name = "P_DEPARTURE_SEQ", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pDEPARTURESEQ,
        @WebParam(name = "P_ARRIVAL_SEQ", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pARRIVALSEQ,
        @WebParam(name = "P_FARE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pFARE,
        @WebParam(name = "P_SEATS", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pSEATS,
        @WebParam(name = "P_QTY", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pQTY,
        @WebParam(name = "P_GENDER", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pGENDER,
        @WebParam(name = "P_NAME", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pNAME,
        @WebParam(name = "P_PHONE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pPHONE,
        @WebParam(name = "P_CNIC", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pCNIC,
        @WebParam(name = "P_REMARK", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pREMARK,
        @WebParam(name = "P_SEAT", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pSEAT
    );

    @WebMethod(action = "http://daewoowsdl.com/getArrivals")
    @RequestWrapper(localName = "getArrivals", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetArrivals")
    @ResponseWrapper(localName = "getArrivalsResponse", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetArrivalsResponse")
    @WebResult(name = "getArrivalsResult", targetNamespace = "http://daewoowsdl.com/")
    public java.lang.String getArrivals(
        @WebParam(name = "CLIENT_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientID,
        @WebParam(name = "CLIENT_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientPASSWORD,
        @WebParam(name = "TERMIANL_DEPARTURE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String termianlDEPARTURE
    );

    @WebMethod(action = "http://daewoowsdl.com/getSeats")
    @RequestWrapper(localName = "getSeats", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetSeats")
    @ResponseWrapper(localName = "getSeatsResponse", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetSeatsResponse")
    @WebResult(name = "getSeatsResult", targetNamespace = "http://daewoowsdl.com/")
    public java.lang.String getSeats(
        @WebParam(name = "CLIENT_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientID,
        @WebParam(name = "CLIENT_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientPASSWORD,
        @WebParam(name = "SCHEDULE_CODE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String scheduleCODE,
        @WebParam(name = "DEPARTURE_SEQ", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String departureSEQ,
        @WebParam(name = "ARRIVAL_SEQ", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String arrivalSEQ,
        @WebParam(name = "DATEA", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String datea,
        @WebParam(name = "DATEB", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String dateb
    );

    @WebMethod(action = "http://daewoowsdl.com/getTicket")
    @RequestWrapper(localName = "getTicket", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetTicket")
    @ResponseWrapper(localName = "getTicketResponse", targetNamespace = "http://daewoowsdl.com/", className = "com.inov8.integration.middleware.daewoo.GetTicketResponse")
    @WebResult(name = "getTicketResult", targetNamespace = "http://daewoowsdl.com/")
    public java.lang.String getTicket(
        @WebParam(name = "CLIENT_TOKEN", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientTOKEN,
        @WebParam(name = "USER_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String userID,
        @WebParam(name = "USER_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String userPASSWORD,
        @WebParam(name = "BOOK_NUMBER", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String bookNUMBER,
        @WebParam(name = "TRANSACTION_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String transactionID,
        @WebParam(name = "TRANSACTION_AMOUNT", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String transactionAMOUNT,
        @WebParam(name = "TRANSACTION_DATE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String transactionDATE,
        @WebParam(name = "TRANSACTION_TIME", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String transactionTIME,
        @WebParam(name = "TRANSACTION_REMARKS", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String transactionREMARKS
    );
}
