
package com.inov8.integration.middleware.daewoo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-11-20T23:12:47.973-08:00
 * Generated source version: 3.1.6
 * 
 */
public final class TmsWSSoap_TmsWSSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://daewoowsdl.com/", "tmsWS");

    private TmsWSSoap_TmsWSSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TmsWS.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TmsWS ss = new TmsWS(wsdlURL, SERVICE_NAME);
        TmsWSSoap port = ss.getTmsWSSoap12();  
        
        {
        System.out.println("Invoking getRoutes...");
        java.lang.String _getRoutes_clientID = "";
        java.lang.String _getRoutes_clientPASSWORD = "";
        java.lang.String _getRoutes_departureDATE = "";
        java.lang.String _getRoutes_departureID = "";
        java.lang.String _getRoutes_arrivalID = "";
        java.lang.String _getRoutes__return = port.getRoutes(_getRoutes_clientID, _getRoutes_clientPASSWORD, _getRoutes_departureDATE, _getRoutes_departureID, _getRoutes_arrivalID);
        System.out.println("getRoutes.result=" + _getRoutes__return);


        }
        {
        System.out.println("Invoking getBookingDetails...");
        java.lang.String _getBookingDetails_clientID = "";
        java.lang.String _getBookingDetails_clientPASSWORD = "";
        java.lang.String _getBookingDetails_bookNUMBER = "";
        java.lang.String _getBookingDetails_phoneNUMBER = "";
        java.lang.String _getBookingDetails__return = port.getBookingDetails(_getBookingDetails_clientID, _getBookingDetails_clientPASSWORD, _getBookingDetails_bookNUMBER, _getBookingDetails_phoneNUMBER);
        System.out.println("getBookingDetails.result=" + _getBookingDetails__return);


        }
        {
        System.out.println("Invoking ctr...");
        java.lang.String _ctr_clientID = "";
        java.lang.String _ctr_clientSECRET = "";
        java.lang.String _ctr_clientPASSWORD = "";
        java.lang.String _ctr__return = port.ctr(_ctr_clientID, _ctr_clientSECRET, _ctr_clientPASSWORD);
        System.out.println("ctr.result=" + _ctr__return);


        }
        {
        System.out.println("Invoking getSeatQuota...");
        java.lang.String _getSeatQuota_clientID = "";
        java.lang.String _getSeatQuota_clientPASSWORD = "";
        java.lang.String _getSeatQuota_scheduleCODE = "";
        java.lang.String _getSeatQuota_quotaDATE = "";
        java.lang.String _getSeatQuota_quotaDEPARTURE = "";
        java.lang.String _getSeatQuota_quotaARRIVAL = "";
        java.lang.String _getSeatQuota__return = port.getSeatQuota(_getSeatQuota_clientID, _getSeatQuota_clientPASSWORD, _getSeatQuota_scheduleCODE, _getSeatQuota_quotaDATE, _getSeatQuota_quotaDEPARTURE, _getSeatQuota_quotaARRIVAL);
        System.out.println("getSeatQuota.result=" + _getSeatQuota__return);


        }
        {
        System.out.println("Invoking getDepartures...");
        java.lang.String _getDepartures_clientID = "";
        java.lang.String _getDepartures_clientPASSWORD = "";
        java.lang.String _getDepartures__return = port.getDepartures(_getDepartures_clientID, _getDepartures_clientPASSWORD);
        System.out.println("getDepartures.result=" + _getDepartures__return);


        }
        {
        System.out.println("Invoking getBooking...");
        java.lang.String _getBooking_clientTOKEN = "";
        java.lang.String _getBooking_userID = "";
        java.lang.String _getBooking_userPASS = "";
        java.lang.String _getBooking_pDATE = "";
        java.lang.String _getBooking_pTIME = "";
        java.lang.String _getBooking_pSCHEDULE = "";
        java.lang.String _getBooking_pTIMECODE = "";
        java.lang.String _getBooking_pROUTE = "";
        java.lang.String _getBooking_pDEPARTURE = "";
        java.lang.String _getBooking_pARRIVAL = "";
        java.lang.String _getBooking_pDEPARTURESEQ = "";
        java.lang.String _getBooking_pARRIVALSEQ = "";
        java.lang.String _getBooking_pFARE = "";
        java.lang.String _getBooking_pSEATS = "";
        java.lang.String _getBooking_pQTY = "";
        java.lang.String _getBooking_pGENDER = "";
        java.lang.String _getBooking_pNAME = "";
        java.lang.String _getBooking_pPHONE = "";
        java.lang.String _getBooking_pCNIC = "";
        java.lang.String _getBooking_pREMARK = "";
        java.lang.String _getBooking_pSEAT = "";
        java.lang.String _getBooking__return = port.getBooking(_getBooking_clientTOKEN, _getBooking_userID, _getBooking_userPASS, _getBooking_pDATE, _getBooking_pTIME, _getBooking_pSCHEDULE, _getBooking_pTIMECODE, _getBooking_pROUTE, _getBooking_pDEPARTURE, _getBooking_pARRIVAL, _getBooking_pDEPARTURESEQ, _getBooking_pARRIVALSEQ, _getBooking_pFARE, _getBooking_pSEATS, _getBooking_pQTY, _getBooking_pGENDER, _getBooking_pNAME, _getBooking_pPHONE, _getBooking_pCNIC, _getBooking_pREMARK, _getBooking_pSEAT);
        System.out.println("getBooking.result=" + _getBooking__return);


        }
        {
        System.out.println("Invoking getArrivals...");
        java.lang.String _getArrivals_clientID = "";
        java.lang.String _getArrivals_clientPASSWORD = "";
        java.lang.String _getArrivals_termianlDEPARTURE = "";
        java.lang.String _getArrivals__return = port.getArrivals(_getArrivals_clientID, _getArrivals_clientPASSWORD, _getArrivals_termianlDEPARTURE);
        System.out.println("getArrivals.result=" + _getArrivals__return);


        }
        {
        System.out.println("Invoking getSeats...");
        java.lang.String _getSeats_clientID = "";
        java.lang.String _getSeats_clientPASSWORD = "";
        java.lang.String _getSeats_scheduleCODE = "";
        java.lang.String _getSeats_departureSEQ = "";
        java.lang.String _getSeats_arrivalSEQ = "";
        java.lang.String _getSeats_datea = "";
        java.lang.String _getSeats_dateb = "";
        java.lang.String _getSeats__return = port.getSeats(_getSeats_clientID, _getSeats_clientPASSWORD, _getSeats_scheduleCODE, _getSeats_departureSEQ, _getSeats_arrivalSEQ, _getSeats_datea, _getSeats_dateb);
        System.out.println("getSeats.result=" + _getSeats__return);


        }
        {
        System.out.println("Invoking getTicket...");
        java.lang.String _getTicket_clientTOKEN = "";
        java.lang.String _getTicket_userID = "";
        java.lang.String _getTicket_userPASSWORD = "";
        java.lang.String _getTicket_bookNUMBER = "";
        java.lang.String _getTicket_transactionID = "";
        java.lang.String _getTicket_transactionAMOUNT = "";
        java.lang.String _getTicket_transactionDATE = "";
        java.lang.String _getTicket_transactionTIME = "";
        java.lang.String _getTicket_transactionREMARKS = "";
        java.lang.String _getTicket__return = port.getTicket(_getTicket_clientTOKEN, _getTicket_userID, _getTicket_userPASSWORD, _getTicket_bookNUMBER, _getTicket_transactionID, _getTicket_transactionAMOUNT, _getTicket_transactionDATE, _getTicket_transactionTIME, _getTicket_transactionREMARKS);
        System.out.println("getTicket.result=" + _getTicket__return);


        }

        System.exit(0);
    }

}
