package com.inov8.integration.middleware.daewoo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-11-20T23:12:48.023-08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://daewoowsdl.com/", name = "tmsWSHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TmsWSHttpPost {

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://daewoowsdl.com/", partName = "Body")
    public java.lang.String getRoutes(
        @WebParam(partName = "CLIENT_ID", name = "CLIENT_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientID,
        @WebParam(partName = "CLIENT_PASSWORD", name = "CLIENT_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientPASSWORD,
        @WebParam(partName = "DEPARTURE_DATE", name = "DEPARTURE_DATE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String departureDATE,
        @WebParam(partName = "DEPARTURE_ID", name = "DEPARTURE_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String departureID,
        @WebParam(partName = "ARRIVAL_ID", name = "ARRIVAL_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String arrivalID
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://daewoowsdl.com/", partName = "Body")
    public java.lang.String getBookingDetails(
        @WebParam(partName = "CLIENT_ID", name = "CLIENT_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientID,
        @WebParam(partName = "CLIENT_PASSWORD", name = "CLIENT_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientPASSWORD,
        @WebParam(partName = "BOOK_NUMBER", name = "BOOK_NUMBER", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String bookNUMBER,
        @WebParam(partName = "PHONE_NUMBER", name = "PHONE_NUMBER", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String phoneNUMBER
    );

    @WebMethod(operationName = "CTR")
    @WebResult(name = "string", targetNamespace = "http://daewoowsdl.com/", partName = "Body")
    public java.lang.String ctr(
        @WebParam(partName = "CLIENT_ID", name = "CLIENT_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientID,
        @WebParam(partName = "CLIENT_SECRET", name = "CLIENT_SECRET", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientSECRET,
        @WebParam(partName = "CLIENT_PASSWORD", name = "CLIENT_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientPASSWORD
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://daewoowsdl.com/", partName = "Body")
    public java.lang.String getSeatQuota(
        @WebParam(partName = "CLIENT_ID", name = "CLIENT_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientID,
        @WebParam(partName = "CLIENT_PASSWORD", name = "CLIENT_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientPASSWORD,
        @WebParam(partName = "SCHEDULE_CODE", name = "SCHEDULE_CODE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String scheduleCODE,
        @WebParam(partName = "QUOTA_DATE", name = "QUOTA_DATE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String quotaDATE,
        @WebParam(partName = "QUOTA_DEPARTURE", name = "QUOTA_DEPARTURE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String quotaDEPARTURE,
        @WebParam(partName = "QUOTA_ARRIVAL", name = "QUOTA_ARRIVAL", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String quotaARRIVAL
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://daewoowsdl.com/", partName = "Body")
    public java.lang.String getDepartures(
        @WebParam(partName = "CLIENT_ID", name = "CLIENT_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientID,
        @WebParam(partName = "CLIENT_PASSWORD", name = "CLIENT_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientPASSWORD
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://daewoowsdl.com/", partName = "Body")
    public java.lang.String getBooking(
        @WebParam(partName = "CLIENT_TOKEN", name = "CLIENT_TOKEN", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientTOKEN,
        @WebParam(partName = "USER_ID", name = "USER_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String userID,
        @WebParam(partName = "USER_PASS", name = "USER_PASS", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String userPASS,
        @WebParam(partName = "P_DATE", name = "P_DATE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pDATE,
        @WebParam(partName = "P_TIME", name = "P_TIME", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pTIME,
        @WebParam(partName = "P_SCHEDULE", name = "P_SCHEDULE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pSCHEDULE,
        @WebParam(partName = "P_TIMECODE", name = "P_TIMECODE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pTIMECODE,
        @WebParam(partName = "P_ROUTE", name = "P_ROUTE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pROUTE,
        @WebParam(partName = "P_DEPARTURE", name = "P_DEPARTURE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pDEPARTURE,
        @WebParam(partName = "P_ARRIVAL", name = "P_ARRIVAL", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pARRIVAL,
        @WebParam(partName = "P_DEPARTURE_SEQ", name = "P_DEPARTURE_SEQ", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pDEPARTURESEQ,
        @WebParam(partName = "P_ARRIVAL_SEQ", name = "P_ARRIVAL_SEQ", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pARRIVALSEQ,
        @WebParam(partName = "P_FARE", name = "P_FARE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pFARE,
        @WebParam(partName = "P_SEATS", name = "P_SEATS", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pSEATS,
        @WebParam(partName = "P_QTY", name = "P_QTY", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pQTY,
        @WebParam(partName = "P_GENDER", name = "P_GENDER", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pGENDER,
        @WebParam(partName = "P_NAME", name = "P_NAME", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pNAME,
        @WebParam(partName = "P_PHONE", name = "P_PHONE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pPHONE,
        @WebParam(partName = "P_CNIC", name = "P_CNIC", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pCNIC,
        @WebParam(partName = "P_REMARK", name = "P_REMARK", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pREMARK,
        @WebParam(partName = "P_SEAT", name = "P_SEAT", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String pSEAT
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://daewoowsdl.com/", partName = "Body")
    public java.lang.String getArrivals(
        @WebParam(partName = "CLIENT_ID", name = "CLIENT_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientID,
        @WebParam(partName = "CLIENT_PASSWORD", name = "CLIENT_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientPASSWORD,
        @WebParam(partName = "TERMIANL_DEPARTURE", name = "TERMIANL_DEPARTURE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String termianlDEPARTURE
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://daewoowsdl.com/", partName = "Body")
    public java.lang.String getSeats(
        @WebParam(partName = "CLIENT_ID", name = "CLIENT_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientID,
        @WebParam(partName = "CLIENT_PASSWORD", name = "CLIENT_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientPASSWORD,
        @WebParam(partName = "SCHEDULE_CODE", name = "SCHEDULE_CODE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String scheduleCODE,
        @WebParam(partName = "DEPARTURE_SEQ", name = "DEPARTURE_SEQ", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String departureSEQ,
        @WebParam(partName = "ARRIVAL_SEQ", name = "ARRIVAL_SEQ", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String arrivalSEQ,
        @WebParam(partName = "DATEA", name = "DATEA", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String datea,
        @WebParam(partName = "DATEB", name = "DATEB", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String dateb
    );

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://daewoowsdl.com/", partName = "Body")
    public java.lang.String getTicket(
        @WebParam(partName = "CLIENT_TOKEN", name = "CLIENT_TOKEN", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String clientTOKEN,
        @WebParam(partName = "USER_ID", name = "USER_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String userID,
        @WebParam(partName = "USER_PASSWORD", name = "USER_PASSWORD", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String userPASSWORD,
        @WebParam(partName = "BOOK_NUMBER", name = "BOOK_NUMBER", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String bookNUMBER,
        @WebParam(partName = "TRANSACTION_ID", name = "TRANSACTION_ID", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String transactionID,
        @WebParam(partName = "TRANSACTION_AMOUNT", name = "TRANSACTION_AMOUNT", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String transactionAMOUNT,
        @WebParam(partName = "TRANSACTION_DATE", name = "TRANSACTION_DATE", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String transactionDATE,
        @WebParam(partName = "TRANSACTION_TIME", name = "TRANSACTION_TIME", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String transactionTIME,
        @WebParam(partName = "TRANSACTION_REMARKS", name = "TRANSACTION_REMARKS", targetNamespace = "http://daewoowsdl.com/")
        java.lang.String transactionREMARKS
    );
}
