package com.inov8.integration.middleware.novatti;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-10-16T11:28:16.133+05:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://soap.api.novatti.com/service", name = "AgentServiceIF")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AgentServiceIF {

    @WebMethod(operationName = "GetSystemStatus")
    @WebResult(name = "SoapSystemStatusResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "SystemStatusResponse")
    public SoapSystemStatusResponse getSystemStatus(
            @WebParam(partName = "SystemStatusRequest", name = "SoapSystemStatusRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapSystemStatusRequest systemStatusRequest
    );

    @WebMethod(operationName = "AgentChangePassword")
    @WebResult(name = "SoapAgentChangePasswordResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "AgentChangePasswordResponse")
    public SoapAgentChangePasswordResponse agentChangePassword(
            @WebParam(partName = "AgentChangePasswordRequest", name = "SoapAgentChangePasswordRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapAgentChangePasswordRequest agentChangePasswordRequest
    );

    @WebMethod(operationName = "GetAgentStructure")
    @WebResult(name = "SoapAgentStructureResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "AgentStructureResponse")
    public SoapAgentStructureResponse getAgentStructure(
            @WebParam(partName = "AgentStructureRequest", name = "SoapAgentStructureRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapAgentStructureRequest agentStructureRequest
    );

    @WebMethod(operationName = "GetAgentProducts")
    @WebResult(name = "SoapAgentProductsResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "AgentProductsResponse")
    public SoapAgentProductsResponse getAgentProducts(
            @WebParam(partName = "AgentProductsRequest", name = "SoapAgentProductsRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapAgentProductsRequest agentProductsRequest
    );

    @WebMethod(operationName = "GetAgentDocuments")
    @WebResult(name = "SoapDocumentsInfoResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "DocumentsInfoResponse")
    public SoapDocumentsInfoResponse getAgentDocuments(
            @WebParam(partName = "DocumentsInfoRequest", name = "SoapDocumentsInfoRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapDocumentsInfoRequest documentsInfoRequest
    );

    @WebMethod(operationName = "AgentLogin")
    @WebResult(name = "SoapAgentLoginResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "AgentLoginResponse")
    public SoapAgentLoginResponse agentLogin(
            @WebParam(partName = "AgentLoginReques", name = "SoapAgentLoginRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapAgentLoginRequest agentLoginReques
    );

    @WebMethod(operationName = "GetAgentAddresses")
    @WebResult(name = "SoapAgentAddressesResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "AgentAddressesResponse")
    public SoapAgentAddressesResponse getAgentAddresses(
            @WebParam(partName = "AgentAddressesRequest", name = "SoapAgentAddressesRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapAgentAddressesRequest agentAddressesRequest
    );

    @WebMethod(operationName = "GetAgentSettlements")
    @WebResult(name = "SoapAgentSettlementResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "AgentSettlementResponse")
    public SoapAgentSettlementResponse getAgentSettlements(
            @WebParam(partName = "AgentSettlementRequest", name = "SoapAgentSettlementRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapAgentSettlementRequest agentSettlementRequest
    );

    @WebMethod(operationName = "AgentWalletTransfer")
    @WebResult(name = "SoapAgentWalletTransferResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "AgentWalletTransferResponse")
    public SoapAgentWalletTransferResponse agentWalletTransfer(
            @WebParam(partName = "AgentWalletTransferRequest", name = "SoapAgentWalletTransferRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapAgentWalletTransferRequest agentWalletTransferRequest
    );

    @WebMethod(operationName = "AgentCreate")
    @WebResult(name = "SoapAgentCreateResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "AgentCreateResponse")
    public SoapAgentCreateResponse agentCreate(
            @WebParam(partName = "AgentCreateRequest", name = "SoapAgentCreateRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapAgentCreateRequest agentCreateRequest
    );

    @WebMethod(operationName = "AgentSearch")
    @WebResult(name = "SoapAgentSearchResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "AgentSearchResponse")
    public SoapAgentSearchResponse agentSearch(
            @WebParam(partName = "AgentSearchRequest", name = "SoapAgentSearchRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapAgentSearchRequest agentSearchRequest
    );

    @WebMethod(operationName = "AgentUpdate")
    @WebResult(name = "SoapAgentUpdateResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "AgentUpdateResponse")
    public SoapAgentUpdateResponse agentUpdate(
            @WebParam(partName = "AgentUpdateRequest", name = "SoapAgentUpdateRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapAgentUpdateRequest agentUpdateRequest
    );

    @WebMethod(operationName = "GetAgentTemplates")
    @WebResult(name = "SoapAgentTemplateResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "AgentTemplateResponse")
    public SoapAgentTemplateResponse getAgentTemplates(
            @WebParam(partName = "AgentTemplateRequest", name = "SoapAgentTemplateRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapAgentTemplateRequest agentTemplateRequest
    );

    @WebMethod(operationName = "SessionValidate")
    @WebResult(name = "SoapSessionValidateResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "SessionValidateResponse")
    public SoapSessionValidateResponse sessionValidate(
            @WebParam(partName = "SessionValidateRequest", name = "SoapSessionValidateRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapSessionValidateRequest sessionValidateRequest
    );

    @WebMethod(operationName = "GetBulletins")
    @WebResult(name = "SoapBulletinInfoResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "BulletinInfoResponse")
    public SoapBulletinInfoResponse getBulletins(
            @WebParam(partName = "BulletinInfoRequest", name = "SoapBulletinInfoRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapBulletinInfoRequest bulletinInfoRequest
    );

    @WebMethod(operationName = "AgentChangeAuthkey")
    @WebResult(name = "SoapAgentChangeAuthkeyResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "AgentChangeAuthkeyResponse")
    public SoapAgentChangeAuthkeyResponse agentChangeAuthkey(
            @WebParam(partName = "AgentChangeAuthkeyRequest", name = "SoapAgentChangeAuthkeyRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapAgentChangeAuthkeyRequest agentChangeAuthkeyRequest
    );

    @WebMethod(operationName = "GetAgentProfile")
    @WebResult(name = "SoapAgentProfileResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "AgentProfileResponse")
    public SoapAgentProfileResponse getAgentProfile(
            @WebParam(partName = "AgentProfileRequest", name = "SoapAgentProfileRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapAgentProfileRequest agentProfileRequest
    );

    @WebMethod(operationName = "GetAgentInfo")
    @WebResult(name = "SoapAgentInfoResponse", targetNamespace = "http://soap.api.novatti.com/types", partName = "AgentInfoResponse")
    public SoapAgentInfoResponse getAgentInfo(
            @WebParam(partName = "AgentInfoRequest", name = "SoapAgentInfoRequest", targetNamespace = "http://soap.api.novatti.com/types")
            SoapAgentInfoRequest agentInfoRequest
    );
}
