
package com.inov8.integration.middleware.novatti;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-10-16T11:28:49.693+05:00
 * Generated source version: 3.1.3
 * 
 */
public final class PurchaseServiceIF_PurchaseServiceIFPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.api.novatti.com/service", "PurchaseService");

    private PurchaseServiceIF_PurchaseServiceIFPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = PurchaseService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PurchaseService ss = new PurchaseService(wsdlURL, SERVICE_NAME);
        PurchaseServiceIF port = ss.getPurchaseServiceIFPort();  
        
        {
        System.out.println("Invoking validateProductRedeem...");
        SoapValidateProductRedeemRequest _validateProductRedeem_validateProductRedeemRequest = null;
        SoapValidateProductRedeemResponse _validateProductRedeem__return = port.validateProductRedeem(_validateProductRedeem_validateProductRedeemRequest);
        System.out.println("validateProductRedeem.result=" + _validateProductRedeem__return);


        }
        {
        System.out.println("Invoking makeProductPurchase...");
        SoapProductPurchaseRequest _makeProductPurchase_productPurchaseRequest = null;
        SoapProductPurchaseResponse _makeProductPurchase__return = port.makeProductPurchase(_makeProductPurchase_productPurchaseRequest);
        System.out.println("makeProductPurchase.result=" + _makeProductPurchase__return);


        }
        {
        System.out.println("Invoking requestPinBatch...");
        SoapPinBatchRequest _requestPinBatch_pinBatchRequest = null;
        SoapPinBatchResponse _requestPinBatch__return = port.requestPinBatch(_requestPinBatch_pinBatchRequest);
        System.out.println("requestPinBatch.result=" + _requestPinBatch__return);


        }
        {
        System.out.println("Invoking makeProductRedeem...");
        SoapMakeProductRedeemRequest _makeProductRedeem_makeProductRedeemRequest = null;
        SoapMakeProductRedeemResponse _makeProductRedeem__return = port.makeProductRedeem(_makeProductRedeem_makeProductRedeemRequest);
        System.out.println("makeProductRedeem.result=" + _makeProductRedeem__return);


        }
        {
        System.out.println("Invoking makePurchaseReprint...");
        SoapPurchaseReprintRequest _makePurchaseReprint_purchaseReprintRequest = null;
        SoapPurchaseReprintResponse _makePurchaseReprint__return = port.makePurchaseReprint(_makePurchaseReprint_purchaseReprintRequest);
        System.out.println("makePurchaseReprint.result=" + _makePurchaseReprint__return);


        }
        {
        System.out.println("Invoking requestPinBatchStatus...");
        SoapPinBatchStatusRequest _requestPinBatchStatus_pinBatchStatusRequest = null;
        SoapPinBatchStatusResponse _requestPinBatchStatus__return = port.requestPinBatchStatus(_requestPinBatchStatus_pinBatchStatusRequest);
        System.out.println("requestPinBatchStatus.result=" + _requestPinBatchStatus__return);


        }
        {
        System.out.println("Invoking receivePinBatch...");
        SoapPinBatchReceiveRequest _receivePinBatch_pinBatchReceiveRequest = null;
        SoapPinBatchReceiveResponse _receivePinBatch__return = port.receivePinBatch(_receivePinBatch_pinBatchReceiveRequest);
        System.out.println("receivePinBatch.result=" + _receivePinBatch__return);


        }
        {
        System.out.println("Invoking makePurchaseRefund...");
        SoapPurchaseRefundRequest _makePurchaseRefund_purchaseRefundRequest = null;
        SoapPurchaseRefundResponse _makePurchaseRefund__return = port.makePurchaseRefund(_makePurchaseRefund_purchaseRefundRequest);
        System.out.println("makePurchaseRefund.result=" + _makePurchaseRefund__return);


        }
        {
        System.out.println("Invoking makePurchaseReversal...");
        SoapPurchaseReversalRequest _makePurchaseReversal_purchaseReversalRequest = null;
        SoapPurchaseReversalResponse _makePurchaseReversal__return = port.makePurchaseReversal(_makePurchaseReversal_purchaseReversalRequest);
        System.out.println("makePurchaseReversal.result=" + _makePurchaseReversal__return);


        }

        System.exit(0);
    }

}
