package com.inov8.integration.middleware.novatti;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-11-04T11:58:24.719+05:00
 * Generated source version: 3.1.3
 * 
 */
@WebServiceClient(name = "ReportsService", 
                  wsdlLocation = "file:reports.wsdl",
                  targetNamespace = "http://soap.api.novatti.com/service") 
public class ReportsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.api.novatti.com/service", "ReportsService");
    public final static QName ReportsServiceIFPort = new QName("http://soap.api.novatti.com/service", "ReportsServiceIFPort");
    static {
        URL url = null;
        try {
            url = new URL("file:reports.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReportsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:reports.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ReportsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReportsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReportsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ReportsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ReportsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ReportsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ReportsServiceIF
     */
    @WebEndpoint(name = "ReportsServiceIFPort")
    public ReportsServiceIF getReportsServiceIFPort() {
        return super.getPort(ReportsServiceIFPort, ReportsServiceIF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReportsServiceIF
     */
    @WebEndpoint(name = "ReportsServiceIFPort")
    public ReportsServiceIF getReportsServiceIFPort(WebServiceFeature... features) {
        return super.getPort(ReportsServiceIFPort, ReportsServiceIF.class, features);
    }

}
