
package com.inov8.integration.middleware.novatti;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2015-11-04T11:58:24.499+05:00
 * Generated source version: 3.1.3
 * 
 */
public final class ReportsServiceIF_ReportsServiceIFPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.api.novatti.com/service", "ReportsService");

    private ReportsServiceIF_ReportsServiceIFPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ReportsService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ReportsService ss = new ReportsService(wsdlURL, SERVICE_NAME);
        ReportsServiceIF port = ss.getReportsServiceIFPort();  
        
        {
        System.out.println("Invoking getTransactionInfo...");
        SoapTransactionInfoRequest _getTransactionInfo_transactionInfoRequest = null;
        SoapTransactionInfoResponse _getTransactionInfo__return = port.getTransactionInfo(_getTransactionInfo_transactionInfoRequest);
        System.out.println("getTransactionInfo.result=" + _getTransactionInfo__return);


        }

        System.exit(0);
    }

}
