package com.inov8.integration.channel.CLSJS.client;

import org.apache.cxf.annotations.EndpointProperty;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2021-07-07T14:04:25.300+05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/Screen_MS", name = "Screen_MSPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@EndpointProperty(key = "soap.no.validate.parts", value = "true")
public interface ScreenMSPortType {

    @WebMethod(operationName = "ScreenOperation", action = "ScreenOperations")
    @WebResult(name = "ImportScreeningResponse", targetNamespace = "http://tempuri.org/Screen_MS", partName = "ImportScreeningResponse")
    public ImportScreeningResponse screenOperation(
        @WebParam(partName = "ImportScreening", name = "ImportScreening", targetNamespace = "http://tempuri.org/Screen_MS")
        ImportScreening importScreening
    );
}
