package com.inov8.integration.channel.CLSJS.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2021-07-07T14:04:25.347+05:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "Screen_MSSOAP_HTTP_Service", 
                  wsdlLocation = "file:cls.wsdl",
                  targetNamespace = "http://tempuri.org/Screen_MS") 
public class ScreenMSSOAPHTTPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/Screen_MS", "Screen_MSSOAP_HTTP_Service");
    public final static QName ScreenMSSOAPHTTPPort = new QName("http://tempuri.org/Screen_MS", "Screen_MSSOAP_HTTP_Port");
    static {
        URL url = null;
        try {
            url = new URL("file:cls.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ScreenMSSOAPHTTPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:cls.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ScreenMSSOAPHTTPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ScreenMSSOAPHTTPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScreenMSSOAPHTTPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ScreenMSSOAPHTTPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ScreenMSSOAPHTTPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ScreenMSSOAPHTTPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ScreenMSPortType
     */
    @WebEndpoint(name = "Screen_MSSOAP_HTTP_Port")
    public ScreenMSPortType getScreenMSSOAPHTTPPort() {
        return super.getPort(ScreenMSSOAPHTTPPort, ScreenMSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScreenMSPortType
     */
    @WebEndpoint(name = "Screen_MSSOAP_HTTP_Port")
    public ScreenMSPortType getScreenMSSOAPHTTPPort(WebServiceFeature... features) {
        return super.getPort(ScreenMSSOAPHTTPPort, ScreenMSPortType.class, features);
    }

}
