package com.inov8.integration.middleware.bop.m3Tech;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-12-23T01:55:19.523-08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "MobileService", 
                  wsdlLocation = "http://172.16.111.120:83/MobileService.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class MobileService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "MobileService");
    public final static QName MobileServiceSoap12 = new QName("http://tempuri.org/", "MobileServiceSoap12");
    public final static QName MobileServiceSoap = new QName("http://tempuri.org/", "MobileServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://172.16.111.120:83/MobileService.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MobileService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.16.111.120:83/MobileService.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MobileService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MobileService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MobileService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MobileService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MobileService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MobileService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MobileServiceSoap
     */
    @WebEndpoint(name = "MobileServiceSoap12")
    public MobileServiceSoap getMobileServiceSoap12() {
        return super.getPort(MobileServiceSoap12, MobileServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MobileServiceSoap
     */
    @WebEndpoint(name = "MobileServiceSoap12")
    public MobileServiceSoap getMobileServiceSoap12(WebServiceFeature... features) {
        return super.getPort(MobileServiceSoap12, MobileServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns MobileServiceSoap
     */
    @WebEndpoint(name = "MobileServiceSoap")
    public MobileServiceSoap getMobileServiceSoap() {
        return super.getPort(MobileServiceSoap, MobileServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MobileServiceSoap
     */
    @WebEndpoint(name = "MobileServiceSoap")
    public MobileServiceSoap getMobileServiceSoap(WebServiceFeature... features) {
        return super.getPort(MobileServiceSoap, MobileServiceSoap.class, features);
    }

}
