
package com.inov8.integration.middleware.bop.m3Tech;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-12-23T01:55:19.465-08:00
 * Generated source version: 3.1.6
 * 
 */
public final class MobileServiceSoap_MobileServiceSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "MobileService");

    private MobileServiceSoap_MobileServiceSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MobileService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MobileService ss = new MobileService(wsdlURL, SERVICE_NAME);
        MobileServiceSoap port = ss.getMobileServiceSoap12();  
        
        {
        System.out.println("Invoking sendSMS...");
        java.lang.String _sendSMS_accessKey = "";
        java.lang.String _sendSMS_mobileNo = "";
        java.lang.String _sendSMS_sms = "";
        java.lang.String _sendSMS_channel = "";
        java.lang.String _sendSMS__return = port.sendSMS(_sendSMS_accessKey, _sendSMS_mobileNo, _sendSMS_sms, _sendSMS_channel);
        System.out.println("sendSMS.result=" + _sendSMS__return);


        }
        {
        System.out.println("Invoking checkRegistration...");
        java.lang.String _checkRegistration_accessKey = "";
        java.lang.String _checkRegistration_cnic = "";
        java.lang.String _checkRegistration__return = port.checkRegistration(_checkRegistration_accessKey, _checkRegistration_cnic);
        System.out.println("checkRegistration.result=" + _checkRegistration__return);


        }

        System.exit(0);
    }

}
