package com.inov8.integration.middleware.bop.m3Tech;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-12-23T01:55:19.519-08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "MobileServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MobileServiceSoap {

    @WebMethod(operationName = "SendSMS", action = "http://tempuri.org/SendSMS")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.m3Tech.SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.m3Tech.SendSMSResponse")
    @WebResult(name = "SendSMSResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String sendSMS(
        @WebParam(name = "AccessKey", targetNamespace = "http://tempuri.org/")
        java.lang.String accessKey,
        @WebParam(name = "MobileNo", targetNamespace = "http://tempuri.org/")
        java.lang.String mobileNo,
        @WebParam(name = "SMS", targetNamespace = "http://tempuri.org/")
        java.lang.String sms,
        @WebParam(name = "Channel", targetNamespace = "http://tempuri.org/")
        java.lang.String channel
    );

    @WebMethod(operationName = "CheckRegistration", action = "http://tempuri.org/CheckRegistration")
    @RequestWrapper(localName = "CheckRegistration", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.m3Tech.CheckRegistration")
    @ResponseWrapper(localName = "CheckRegistrationResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.m3Tech.CheckRegistrationResponse")
    @WebResult(name = "CheckRegistrationResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String checkRegistration(
        @WebParam(name = "AccessKey", targetNamespace = "http://tempuri.org/")
        java.lang.String accessKey,
        @WebParam(name = "CNIC", targetNamespace = "http://tempuri.org/")
        java.lang.String cnic
    );
}
