package com.inov8.integration.middleware.nadra.otc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-09-20T14:40:02.757+05:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "BioVeriSysOTC", 
                  wsdlLocation = "file:BioVeriSysOTCTransaction.wsdl",
                  targetNamespace = "http://NADRA.Biometric.Verification") 
public class BioVeriSysOTC extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://NADRA.Biometric.Verification", "BioVeriSysOTC");
    public final static QName BasicHttpBindingIBioVeriSysOTC = new QName("http://NADRA.Biometric.Verification", "BasicHttpBinding_IBioVeriSysOTC");
    static {
        URL url = null;
        try {
            url = new URL("file:BioVeriSysOTCTransaction.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BioVeriSysOTC.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:BioVeriSysOTCTransaction.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BioVeriSysOTC(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BioVeriSysOTC(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BioVeriSysOTC() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BioVeriSysOTC(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BioVeriSysOTC(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BioVeriSysOTC(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IBioVeriSysOTC
     */
    @WebEndpoint(name = "BasicHttpBinding_IBioVeriSysOTC")
    public IBioVeriSysOTC getBasicHttpBindingIBioVeriSysOTC() {
        return super.getPort(BasicHttpBindingIBioVeriSysOTC, IBioVeriSysOTC.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBioVeriSysOTC
     */
    @WebEndpoint(name = "BasicHttpBinding_IBioVeriSysOTC")
    public IBioVeriSysOTC getBasicHttpBindingIBioVeriSysOTC(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIBioVeriSysOTC, IBioVeriSysOTC.class, features);
    }

}
