package com.inov8.integration.middleware.nadra.otc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-09-20T14:40:02.698+05:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://NADRA.Biometric.Verification", name = "IBioVeriSysOTC")
@XmlSeeAlso({ObjectFactory.class})
public interface IBioVeriSysOTC {

    @WebMethod(operationName = "VerifyFingerPrints", action = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/VerifyFingerPrints")
    @Action(input = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/VerifyFingerPrints", output = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/VerifyFingerPrintsResponse")
    @RequestWrapper(localName = "VerifyFingerPrints", targetNamespace = "http://NADRA.Biometric.Verification", className = "com.inov8.integration.middleware.nadra.otc.VerifyFingerPrints")
    @ResponseWrapper(localName = "VerifyFingerPrintsResponse", targetNamespace = "http://NADRA.Biometric.Verification", className = "com.inov8.integration.middleware.nadra.otc.VerifyFingerPrintsResponse")
    @WebResult(name = "VerifyFingerPrintsResult", targetNamespace = "http://NADRA.Biometric.Verification")
    public java.lang.String verifyFingerPrints(
        @WebParam(name = "franchizeID", targetNamespace = "http://NADRA.Biometric.Verification")
        java.lang.String franchizeID,
        @WebParam(name = "xml_request_data", targetNamespace = "http://NADRA.Biometric.Verification")
        java.lang.String xmlRequestData
    );

    @WebMethod(operationName = "GetCitizenIdentityDemographicsData", action = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/GetCitizenIdentityDemographicsData")
    @Action(input = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/GetCitizenIdentityDemographicsData", output = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/GetCitizenIdentityDemographicsDataResponse")
    @RequestWrapper(localName = "GetCitizenIdentityDemographicsData", targetNamespace = "http://NADRA.Biometric.Verification", className = "com.inov8.integration.middleware.nadra.otc.GetCitizenIdentityDemographicsData")
    @ResponseWrapper(localName = "GetCitizenIdentityDemographicsDataResponse", targetNamespace = "http://NADRA.Biometric.Verification", className = "com.inov8.integration.middleware.nadra.otc.GetCitizenIdentityDemographicsDataResponse")
    @WebResult(name = "GetCitizenIdentityDemographicsDataResult", targetNamespace = "http://NADRA.Biometric.Verification")
    public java.lang.String getCitizenIdentityDemographicsData(
        @WebParam(name = "franchizeID", targetNamespace = "http://NADRA.Biometric.Verification")
        java.lang.String franchizeID,
        @WebParam(name = "xml_request_data", targetNamespace = "http://NADRA.Biometric.Verification")
        java.lang.String xmlRequestData
    );

    @WebMethod(operationName = "TestService", action = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/TestService")
    @Action(input = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/TestService", output = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/TestServiceResponse")
    @RequestWrapper(localName = "TestService", targetNamespace = "http://NADRA.Biometric.Verification", className = "com.inov8.integration.middleware.nadra.otc.TestService")
    @ResponseWrapper(localName = "TestServiceResponse", targetNamespace = "http://NADRA.Biometric.Verification", className = "com.inov8.integration.middleware.nadra.otc.TestServiceResponse")
    @WebResult(name = "TestServiceResult", targetNamespace = "http://NADRA.Biometric.Verification")
    public java.lang.String testService(
        @WebParam(name = "type", targetNamespace = "http://NADRA.Biometric.Verification")
        com.inov8.integration.middleware.nadra.otc.TemplateType type,
        @WebParam(name = "rmtType", targetNamespace = "http://NADRA.Biometric.Verification")
        com.inov8.integration.middleware.nadra.otc.RemittanceType rmtType,
        @WebParam(name = "tempType", targetNamespace = "http://NADRA.Biometric.Verification")
        java.lang.String tempType
    );

    @WebMethod(operationName = "VerifyPhotograph", action = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/VerifyPhotograph")
    @Action(input = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/VerifyPhotograph", output = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/VerifyPhotographResponse")
    @RequestWrapper(localName = "VerifyPhotograph", targetNamespace = "http://NADRA.Biometric.Verification", className = "com.inov8.integration.middleware.nadra.otc.VerifyPhotograph")
    @ResponseWrapper(localName = "VerifyPhotographResponse", targetNamespace = "http://NADRA.Biometric.Verification", className = "com.inov8.integration.middleware.nadra.otc.VerifyPhotographResponse")
    @WebResult(name = "VerifyPhotographResult", targetNamespace = "http://NADRA.Biometric.Verification")
    public java.lang.String verifyPhotograph(
        @WebParam(name = "franchizeID", targetNamespace = "http://NADRA.Biometric.Verification")
        java.lang.String franchizeID,
        @WebParam(name = "xml_request_data", targetNamespace = "http://NADRA.Biometric.Verification")
        java.lang.String xmlRequestData
    );

    @WebMethod(operationName = "GetLastVerificationResults", action = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/GetLastVerificationResults")
    @Action(input = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/GetLastVerificationResults", output = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/GetLastVerificationResultsResponse")
    @RequestWrapper(localName = "GetLastVerificationResults", targetNamespace = "http://NADRA.Biometric.Verification", className = "com.inov8.integration.middleware.nadra.otc.GetLastVerificationResults")
    @ResponseWrapper(localName = "GetLastVerificationResultsResponse", targetNamespace = "http://NADRA.Biometric.Verification", className = "com.inov8.integration.middleware.nadra.otc.GetLastVerificationResultsResponse")
    @WebResult(name = "GetLastVerificationResultsResult", targetNamespace = "http://NADRA.Biometric.Verification")
    public java.lang.String getLastVerificationResults(
        @WebParam(name = "franchizeID", targetNamespace = "http://NADRA.Biometric.Verification")
        java.lang.String franchizeID,
        @WebParam(name = "xml_request_data", targetNamespace = "http://NADRA.Biometric.Verification")
        java.lang.String xmlRequestData
    );

    @WebMethod(operationName = "SubmitManualVerificationResults", action = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/SubmitManualVerificationResults")
    @Action(input = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/SubmitManualVerificationResults", output = "http://NADRA.Biometric.Verification/IBioVeriSysOTC/SubmitManualVerificationResultsResponse")
    @RequestWrapper(localName = "SubmitManualVerificationResults", targetNamespace = "http://NADRA.Biometric.Verification", className = "com.inov8.integration.middleware.nadra.otc.SubmitManualVerificationResults")
    @ResponseWrapper(localName = "SubmitManualVerificationResultsResponse", targetNamespace = "http://NADRA.Biometric.Verification", className = "com.inov8.integration.middleware.nadra.otc.SubmitManualVerificationResultsResponse")
    @WebResult(name = "SubmitManualVerificationResultsResult", targetNamespace = "http://NADRA.Biometric.Verification")
    public java.lang.String submitManualVerificationResults(
        @WebParam(name = "franchizeID", targetNamespace = "http://NADRA.Biometric.Verification")
        java.lang.String franchizeID,
        @WebParam(name = "xml_request_data", targetNamespace = "http://NADRA.Biometric.Verification")
        java.lang.String xmlRequestData
    );
}
