
package com.inov8.integration.middleware.abl.smsservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-11-16T03:18:24.261-08:00
 * Generated source version: 3.1.6
 * 
 */
public final class IService_BasicHttpBindingIService_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Service");

    private IService_BasicHttpBindingIService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Service ss = new Service(wsdlURL, SERVICE_NAME);
        IService port = ss.getBasicHttpBindingIService();  
        
        {
        System.out.println("Invoking getDataUsingDataContract...");
        com.inov8.integration.middleware.abl.smsservice.CompositeType _getDataUsingDataContract_composite = null;
        com.inov8.integration.middleware.abl.smsservice.CompositeType _getDataUsingDataContract__return = port.getDataUsingDataContract(_getDataUsingDataContract_composite);
        System.out.println("getDataUsingDataContract.result=" + _getDataUsingDataContract__return);


        }
        {
        System.out.println("Invoking insertAlert...");
        java.lang.String _insertAlert_userId = "";
        java.lang.String _insertAlert_applicationId = "";
        java.lang.String _insertAlert_mobileNo = "";
        java.lang.String _insertAlert_smsbody = "";
        java.lang.String _insertAlert__return = port.insertAlert(_insertAlert_userId, _insertAlert_applicationId, _insertAlert_mobileNo, _insertAlert_smsbody);
        System.out.println("insertAlert.result=" + _insertAlert__return);


        }

        System.exit(0);
    }

}
