package com.inov8.integration.middleware.abl.smsservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-11-16T03:18:24.364-08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IService")
@XmlSeeAlso({ObjectFactory.class})
public interface IService {

    @WebMethod(operationName = "GetDataUsingDataContract", action = "http://tempuri.org/IService/GetDataUsingDataContract")
    @Action(input = "http://tempuri.org/IService/GetDataUsingDataContract", output = "http://tempuri.org/IService/GetDataUsingDataContractResponse")
    @RequestWrapper(localName = "GetDataUsingDataContract", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.smsservice.GetDataUsingDataContract")
    @ResponseWrapper(localName = "GetDataUsingDataContractResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.smsservice.GetDataUsingDataContractResponse")
    @WebResult(name = "GetDataUsingDataContractResult", targetNamespace = "http://tempuri.org/")
    public com.inov8.integration.middleware.abl.smsservice.CompositeType getDataUsingDataContract(
        @WebParam(name = "composite", targetNamespace = "http://tempuri.org/")
        com.inov8.integration.middleware.abl.smsservice.CompositeType composite
    );

    @WebMethod(action = "http://tempuri.org/IService/insertAlert")
    @Action(input = "http://tempuri.org/IService/insertAlert", output = "http://tempuri.org/IService/insertAlertResponse")
    @RequestWrapper(localName = "insertAlert", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.smsservice.InsertAlert")
    @ResponseWrapper(localName = "insertAlertResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.abl.smsservice.InsertAlertResponse")
    @WebResult(name = "insertAlertResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String insertAlert(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        java.lang.String userId,
        @WebParam(name = "applicationId", targetNamespace = "http://tempuri.org/")
        java.lang.String applicationId,
        @WebParam(name = "mobileNo", targetNamespace = "http://tempuri.org/")
        java.lang.String mobileNo,
        @WebParam(name = "smsbody", targetNamespace = "http://tempuri.org/")
        java.lang.String smsbody
    );
}
