package com.inov8.integration.middleware.translitration.IdeaService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2017-04-11T16:20:11.995+05:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://softwarebydefault.com", name = "IdeaUToEServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface IdeaUToEServiceSoap {

    @WebMethod(operationName = "U_To_E", action = "http://softwarebydefault.com/HelloWorld")
    @RequestWrapper(localName = "U_To_E", targetNamespace = "http://softwarebydefault.com", className = "com.inov8.integration.middleware.translitration.UToE")
    @ResponseWrapper(localName = "U_To_EResponse", targetNamespace = "http://softwarebydefault.com", className = "com.inov8.integration.middleware.translitration.UToEResponse")
    @WebResult(name = "U_To_EResult", targetNamespace = "http://softwarebydefault.com")
    public String uToE(
            @WebParam(name = "username", targetNamespace = "http://softwarebydefault.com")
                    String username,
            @WebParam(name = "password", targetNamespace = "http://softwarebydefault.com")
                    String password,
            @WebParam(name = "request", targetNamespace = "http://softwarebydefault.com")
                    String request
    );
}
