package com.inov8.integration.middleware.jsnadra;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-08-20T11:49:34.194+05:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "JSNadraWebServiceHttpService", 
                  wsdlLocation = "file:nadra.wsdl",
                  targetNamespace = "http://JSNadraWebService") 
public class JSNadraWebServiceHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://JSNadraWebService", "JSNadraWebServiceHttpService");
    public final static QName JSNadraWebServiceHttpPort = new QName("http://JSNadraWebService", "JSNadraWebServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:nadra.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JSNadraWebServiceHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:nadra.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public JSNadraWebServiceHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JSNadraWebServiceHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JSNadraWebServiceHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public JSNadraWebServiceHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public JSNadraWebServiceHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public JSNadraWebServiceHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns JSNadraWebService
     */
    @WebEndpoint(name = "JSNadraWebServiceHttpPort")
    public JSNadraWebService getJSNadraWebServiceHttpPort() {
        return super.getPort(JSNadraWebServiceHttpPort, JSNadraWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JSNadraWebService
     */
    @WebEndpoint(name = "JSNadraWebServiceHttpPort")
    public JSNadraWebService getJSNadraWebServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(JSNadraWebServiceHttpPort, JSNadraWebService.class, features);
    }

}
