package com.inov8.integration.middleware.jsnadra;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-08-20T11:49:34.150+05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://JSNadraWebService", name = "JSNadraWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface JSNadraWebService {

    @WebMethod(operationName = "VerifyFingerPrints", action = "http://JSNadraWebService/VerifyFingerPrints")
    @RequestWrapper(localName = "VerifyFingerPrints", targetNamespace = "http://JSNadraWebService", className = "com.inov8.integration.middleware.jsnadra.VerifyFingerPrints")
    @ResponseWrapper(localName = "VerifyFingerPrintsResponse", targetNamespace = "http://JSNadraWebService", className = "com.inov8.integration.middleware.jsnadra.VerifyFingerPrintsResponse")
    @WebResult(name = "VerifyFingerPrintsResult", targetNamespace = "")
    public java.lang.String verifyFingerPrints(
        @WebParam(name = "franchizeID", targetNamespace = "")
        java.lang.String franchizeID,
        @WebParam(name = "xml_request_data", targetNamespace = "")
        java.lang.String xmlRequestData
    );

    @WebMethod(operationName = "GetCitizenData", action = "http://JSNadraWebService/GetCitizenData")
    @RequestWrapper(localName = "GetCitizenData", targetNamespace = "http://JSNadraWebService", className = "com.inov8.integration.middleware.jsnadra.GetCitizenData")
    @ResponseWrapper(localName = "GetCitizenDataResponse", targetNamespace = "http://JSNadraWebService", className = "com.inov8.integration.middleware.jsnadra.GetCitizenDataResponse")
    @WebResult(name = "GetCitizenDataResult", targetNamespace = "")
    public java.lang.String getCitizenData(
        @WebParam(name = "franchizeID", targetNamespace = "")
        java.lang.String franchizeID,
        @WebParam(name = "xml_request_data", targetNamespace = "")
        java.lang.String xmlRequestData
    );

    @WebMethod(operationName = "VerifyFingerPrintsOTC", action = "http://JSNadraWebService/VerifyFingerPrintsOTC")
    @RequestWrapper(localName = "VerifyFingerPrintsOTC", targetNamespace = "http://JSNadraWebService", className = "com.inov8.integration.middleware.jsnadra.VerifyFingerPrintsOTC")
    @ResponseWrapper(localName = "VerifyFingerPrintsOTCResponse", targetNamespace = "http://JSNadraWebService", className = "com.inov8.integration.middleware.jsnadra.VerifyFingerPrintsOTCResponse")
    @WebResult(name = "VerifyFingerPrintsOTCResult", targetNamespace = "")
    public java.lang.String verifyFingerPrintsOTC(
        @WebParam(name = "franchizeID", targetNamespace = "")
        java.lang.String franchizeID,
        @WebParam(name = "xml_request_data", targetNamespace = "")
        java.lang.String xmlRequestData
    );
}
