package com.inov8.integration.middleware.cameoo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "ws_CardRequest_test", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface WsCardRequestSoap {


    /**
     * @param cardID
     * @param pwd
     * @param userID
     * @return returns int
     */
    @WebMethod(operationName = "GetCardBalance", action = "http://tempuri.org/GetCardBalance")
    @WebResult(name = "GetCardBalanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCardBalance", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCardBalance")
    @ResponseWrapper(localName = "GetCardBalanceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCardBalanceResponse")
    public int getCardBalance(
            @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
                    String userID,
            @WebParam(name = "PWD", targetNamespace = "http://tempuri.org/")
                    String pwd,
            @WebParam(name = "CardID", targetNamespace = "http://tempuri.org/")
                    int cardID);

    /**
     * @param pwd
     * @param userID
     * @return returns org.tempuri.ArrayOfCardBalance
     */
    @WebMethod(operationName = "GetCardBalanceList", action = "http://tempuri.org/GetCardBalanceList")
    @WebResult(name = "GetCardBalanceListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCardBalanceList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCardBalanceList")
    @ResponseWrapper(localName = "GetCardBalanceListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCardBalanceListResponse")
    public ArrayOfCardBalance getCardBalanceList(
            @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
                    String userID,
            @WebParam(name = "PWD", targetNamespace = "http://tempuri.org/")
                    String pwd);

    /**
     * @param trnID
     * @param cardID
     * @param qnty
     * @param pwd
     * @param userID
     * @return returns org.tempuri.CardRequest
     */
    @WebMethod(operationName = "RequestCard", action = "http://tempuri.org/RequestCard")
    @WebResult(name = "RequestCardResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RequestCard", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RequestCard")
    @ResponseWrapper(localName = "RequestCardResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RequestCardResponse")
    public CardRequest requestCard(
            @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
                    String userID,
            @WebParam(name = "PWD", targetNamespace = "http://tempuri.org/")
                    String pwd,
            @WebParam(name = "CardID", targetNamespace = "http://tempuri.org/")
                    int cardID,
            @WebParam(name = "TrnID", targetNamespace = "http://tempuri.org/")
                    String trnID,
            @WebParam(name = "Qnty", targetNamespace = "http://tempuri.org/")
                    int qnty);

    /**
     * @param refID
     * @param pwd
     * @param userID
     * @return returns org.tempuri.CardRequest
     */
    @WebMethod(operationName = "ConfirmOrder", action = "http://tempuri.org/ConfirmOrder")
    @WebResult(name = "ConfirmOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConfirmOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConfirmOrder")
    @ResponseWrapper(localName = "ConfirmOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConfirmOrderResponse")
    public CardRequest confirmOrder(
            @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
                    String userID,
            @WebParam(name = "PWD", targetNamespace = "http://tempuri.org/")
                    String pwd,
            @WebParam(name = "RefID", targetNamespace = "http://tempuri.org/")
                    String refID);

    /**
     * @param refID
     * @param pwd
     * @param userID
     * @return returns org.tempuri.CardRequest
     */
    @WebMethod(operationName = "GetOrderPins", action = "http://tempuri.org/GetOrderPins")
    @WebResult(name = "GetOrderPinsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOrderPins", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderPins")
    @ResponseWrapper(localName = "GetOrderPinsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOrderPinsResponse")
    public CardRequest getOrderPins(
            @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
                    String userID,
            @WebParam(name = "PWD", targetNamespace = "http://tempuri.org/")
                    String pwd,
            @WebParam(name = "RefID", targetNamespace = "http://tempuri.org/")
                    String refID);

    /**
     * @param refID
     * @param pwd
     * @param userID
     * @return returns org.tempuri.CardRequest
     */
    @WebMethod(operationName = "CancelOrder", action = "http://tempuri.org/CancelOrder")
    @WebResult(name = "CancelOrderResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelOrder", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelOrder")
    @ResponseWrapper(localName = "CancelOrderResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelOrderResponse")
    public CardRequest cancelOrder(
            @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
                    String userID,
            @WebParam(name = "PWD", targetNamespace = "http://tempuri.org/")
                    String pwd,
            @WebParam(name = "RefID", targetNamespace = "http://tempuri.org/")
                    String refID);

}
