
package com.inov8.integration.middleware.cameoo;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ws_CardRequest_test", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://www.cameoo.com/ws/ws_CardRequest_test.asmx?WSDL")
public class WsCardRequest
        extends Service {
    public WsCardRequest(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsCardRequest(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns WsCardRequestSoap
     */
    @WebEndpoint(name = "ws_CardRequest_testSoap")
    public WsCardRequestSoap getWsCardRequestSoap(QName serviceName) {
        return super.getPort(serviceName, WsCardRequestSoap.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns WsCardRequestSoap
     */
    @WebEndpoint(name = "ws_CardRequest_testSoap")
    public WsCardRequestSoap getWsCardRequestSoap(QName serviceName, WebServiceFeature... features) {
        return super.getPort(serviceName, WsCardRequestSoap.class, features);
    }


}
