package com.inov8.integration.middleware.bop.IExternalCommunication;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2017-08-24T18:32:26.303+05:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "ExternalCommunication", 
                  wsdlLocation = "file:PTIB.wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class ExternalCommunication extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "ExternalCommunication");
    public final static QName WSHttpBindingIExternalCommunication = new QName("http://tempuri.org/", "WSHttpBinding_IExternalCommunication");
    static {
        URL url = null;
        try {
            url = new URL("file:PTIB.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExternalCommunication.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:PTIB.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ExternalCommunication(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExternalCommunication(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExternalCommunication() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ExternalCommunication(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ExternalCommunication(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ExternalCommunication(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IExternalCommunication
     */
    @WebEndpoint(name = "WSHttpBinding_IExternalCommunication")
    public IExternalCommunication getWSHttpBindingIExternalCommunication() {
        return super.getPort(WSHttpBindingIExternalCommunication, IExternalCommunication.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IExternalCommunication
     */
    @WebEndpoint(name = "WSHttpBinding_IExternalCommunication")
    public IExternalCommunication getWSHttpBindingIExternalCommunication(WebServiceFeature... features) {
        return super.getPort(WSHttpBindingIExternalCommunication, IExternalCommunication.class, features);
    }

}
