
package com.inov8.integration.middleware.bop.IExternalCommunication;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2017-08-24T18:32:26.232+05:00
 * Generated source version: 3.1.5
 * 
 */
public final class IExternalCommunication_WSHttpBindingIExternalCommunication_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "ExternalCommunication");

    private IExternalCommunication_WSHttpBindingIExternalCommunication_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ExternalCommunication.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ExternalCommunication ss = new ExternalCommunication(wsdlURL, SERVICE_NAME);
        IExternalCommunication port = ss.getWSHttpBindingIExternalCommunication();  
        
        {
        System.out.println("Invoking saveData...");
        com.inov8.integration.middleware.bop.IExternalCommunication.TransactionData _saveData_tranData = null;
        Short _saveData__return = port.saveData(_saveData_tranData);
        System.out.println("saveData.result=" + _saveData__return);


        }

        System.exit(0);
    }

}
