package com.inov8.integration.middleware.bop.IExternalCommunication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2017-08-24T18:32:26.294+05:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IExternalCommunication")
@XmlSeeAlso({ObjectFactory.class})
public interface IExternalCommunication {

    @WebMethod(operationName = "SaveData", action = "http://tempuri.org/IExternalCommunication/SaveData")
    @Action(input = "http://tempuri.org/IExternalCommunication/SaveData", output = "http://tempuri.org/IExternalCommunication/SaveDataResponse")
    @RequestWrapper(localName = "SaveData", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.IExternalCommunication.SaveData")
    @ResponseWrapper(localName = "SaveDataResponse", targetNamespace = "http://tempuri.org/", className = "com.inov8.integration.middleware.bop.IExternalCommunication.SaveDataResponse")
    @WebResult(name = "SaveDataResult", targetNamespace = "http://tempuri.org/")
    public Short saveData(
            @WebParam(name = "TranData", targetNamespace = "http://tempuri.org/")
                    com.inov8.integration.middleware.bop.IExternalCommunication.TransactionData tranData
    );
}
