package com.inov8.microbank.common.util;

public interface CustomInputTypeContants {
	 String AGENT_MSISDN = "AGENT_MSISDN";
	 String CUSTOMER_MSISDN = "CUSTOMER_MSISDN";
	 String CW_AMOUNT = "CW_AMOUNT";
	 String TRANSACTION_ID = "TRANSACTION_ID";//ID
	 String TRANSACTION_CODE = "TRANSACTION_CODE";//PIN
	 String PIN = "PIN";
	 String BAL_CHECK = "BAL_CHECK";
	 String CD_AMOUNT = "CD_AMOUNT";
	 String CNIC = "CNIC";
	 String MSISDN = "MSISDN";
	 String BP_CONSUMER_NUMBER = "BP_CONSUMER_NUMBER";
	 String UTILITY_TELEPHONE = "UTILITY_TELEPHONE";
	 String UTILITY_PTCL = "UTILITY_PTCL";
	 String UTILITY_MOBILE = "UTILITY_MOBILE";
	 String UTILITY_GAS = "UTILITY_GAS";
	 String UTILITY_ELECTRICITY = "UTILITY_ELECTRICITY";
	 String UTILITY_INTERNET = "UTILITY_INTERNET";	
	 String UTILITY_WATER = "UTILITY_WATER";
	 String UTILITY_MUNICIPAL = "UTILITY_MUNICIPAL";
	 String NEW_PIN="NEW_PIN";
	 String CONFIRM_NEW_PIN="CONFIRM_NEW_PIN";

	 String SENDER_CNIC ="SENDER_CNIC";
	 String CUSTOMER_ID="CUSTOMER_ID";
	 String PAYMENT_MODE="PMODE";
	 String BILL_AMOUNT = "BAMT";
	 String CUSTOMER_BILL_AMOUNT = "BP_AMOUNT";


	 String TRANSFER_IN_AMOUNT="TRANSFER_IN_AMOUNT";
	 String TRANSFER_OUT_AMOUNT="TRANSFER_OUT_AMOUNT";
	 String JCASH_ACCOUNT_NO = "JCASH_ACCOUNT";
	 String LPIN = "LPIN";
	 String CHALLANID = "CHALLANID";
	 String RECEIVER_ACCOUNT_NO = "RACNO";
	 String UTILITY_PREPAID = "PREPAID";
	 String UTILITY_POSTPAID = "POSTPAID";
	 String VERIFY_OTP = "VERIFY_OTP";
	 String CNIC_AMOUNT = "CNIC_AMOUNT";
	 String WALLET_AMOUNT = "WALLET_AMOUNT";
     String CORE_AMOUNT = "CORE_AMOUNT";
	 String RECEIVER_CNIC = "RECEIVER_CNIC";
     String CORE_ACC_NO = "CORE_ACC_NO";
	 String GOV_PAYMENTS = "GOV_PAYMENTS";




}
