package com.inov8.microbank.common.util;

public class XPathConstants
{
	public static final String actionLogInputXMLLocationSteps[] = { /* "//param[@name='PIN']", */ "//param[@name='NPIN']","//param[@name='CPIN']","//param[@name='CVV']","//param[@name='TPIN']"};
	public static final String actionLogOutputXMLLocationSteps[] = { /* "//param[@name='PIN']", */ "//param[@name='NPIN']","//param[@name='CPIN']","//param[@name='CVV']","//param[@name='TPIN']"};

	public static final String kasbBillPaymentDispenserAuditLogInputParamLocationSteps[] = {"//receivingAcctNo","//payingAccNo","//tPin"};

	public static final String veriflyManagerAuditLogInputParamLocationSteps[] = {"com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountNo","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/cardNo","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/cardExpiryDate","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/newPin","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/oldPin","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/generatedPin", /* "com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/pin", */ "com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountInfoIdLogModelList/owner/pin","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountInfoIdLogModelList/owner/accountNo","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountInfoIdLogModelList/owner/cardNo","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountInfoIdLogModelList/owner/cardExpiryDate","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountInfoIdLogModelList/owner/newPin","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountInfoIdLogModelList/owner/oldPin","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountInfoIdLogModelList/owner/generatedPin"};
	public static final String veriflyManagerAuditLogOutputParamLocationSteps[] = {"com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountNo","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/cardNo","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/cardExpiryDate","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/newPin","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/oldPin","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/generatedPin", /* "com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/pin", */ "com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountInfoIdLogModelList/owner/pin","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountInfoIdLogModelList/owner/accountNo","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountInfoIdLogModelList/owner/cardNo","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountInfoIdLogModelList/owner/cardExpiryDate","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountInfoIdLogModelList/owner/newPin","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountInfoIdLogModelList/owner/oldPin","com.inov8.verifly.common.wrapper.VeriflyBaseWrapperImpl/accountInfoModel/accountInfoIdLogModelList/owner/generatedPin"};
	
	public static final String PhoenixAuditLogInputParamLocationSteps[] = {"com.inov8.microbank.server.service.switchmodule.iris.model.PhoenixIntegrationMessageVO/accountNumber","com.inov8.microbank.server.service.switchmodule.iris.model.PhoenixIntegrationMessageVO/accountDetail", "com.inov8.microbank.server.service.switchmodule.iris.model.PhoenixIntegrationMessageVO/secureVerificationData","com.inov8.microbank.server.service.switchmodule.iris.model.PhoenixIntegrationMessageVO/customerIdentification","com.inov8.microbank.server.service.switchmodule.iris.model.PhoenixIntegrationMessageVO/cardNumber","com.inov8.microbank.server.service.switchmodule.iris.model.PhoenixIntegrationMessageVO/customerPINData","com.inov8.microbank.server.service.switchmodule.iris.model.PhoenixIntegrationMessageVO/newPIN","com.inov8.microbank.server.service.switchmodule.iris.model.PhoenixIntegrationMessageVO/accountDetail"};
	
	public static final String AtlasAuditLogInputParamLocationSteps[] = {"com.inov8.microbank.server.service.switchmodule.iris.model.IRISIntegrationMessageVO/secureVerificationData","com.inov8.microbank.server.service.switchmodule.iris.model.IRISIntegrationMessageVO/fromCustomerAccount/number","com.inov8.microbank.server.service.switchmodule.iris.model.IRISIntegrationMessageVO/channelUserIdentification"};
}


